### ISSUE TITLE
{error, {closed, HTML}} with connection: close

### ISSUE THREAD

**Issue by rlipscombe** [benoitc/hackney#148]
I'm using hackney to talk to a fairly simple HTTP server -- specifically this one: http://empeg-hijack.sourceforge.net/, as it happens.

It uses `Connection: close` semantics, which -- somehow -- seem to confuse hackney. If I look in wireshark, I see what looks like a completely valid HTTP conversation -- I see:

    HTTP/1.1 200 OK
    Connection: close
    Content-Type: text/html

    ...the expected HTML...

That packet has FIN/PSH/ACK set, thus closing the connection. I'm using the following Erlang to issue the request:

    Url = "http://10.0.0.21".
    {ok, Status, Headers, Ref} = hackney:get(Url).
    hackney:body(Ref).

Instead of returning {ok, HTML}, the call to `hackney:body` returns `{error,{closed, HTML}}` instead.

**Comment by benoitc** [comment]
Sorry for the late response, I didn't saw this ticket until now... Anyway such response si expected when the the `Content-Length` or a `Transfer-encoding` is set. Maybe i should change the response in that case.

**Comment by rlipscombe** [comment]
Well, yes. The documentation says that `{ok, Body} = hackney:body(Client)`. This needs to be the same for all responses where there _is_ a body.

**Comment by benoitc** [comment]
fixed in 4584f8798277ec7568e6b84e1d68ed9a8b44696d
