### ISSUE TITLE
1.0.5 broke API when response has no body

### ISSUE THREAD

**Issue by sdepold** [benoitc/hackney#153]
When you request an endpoint that has no content, then the return value of hackney used to be

```erlang
{ok, StatusCode, RespHeaders, ClientRef}
```

whereas it is

```erlang
{ok, StatusCode, RespHeaders}
```

for 1.0.5. An example endpoint is here https://developer.github.com/v3/gists/comments/#delete-a-comment

**Comment by benoitc** [comment]
In latest master? 

on HEAD this is expected in 1.0.5. The 204 response has been added recently in 62f768fa38c4f9aa5bcb4e9cec084c4d94273bdf via #151 . Maybe instead of returning a different response we should instead returning an empty body directly. cc @lexmag cc@edgurgel

**Comment by sdepold** [comment]
+1 for empty body.

**Comment by edgurgel** [comment]
I agree as it won't break the API. Unless you want to increase the MAJOR version it should keep the client with an empty body. :+1:

**Comment by lexmag** [comment]
Right, that was the question in #151:
> The returning tuple for this response changes to {ok, Status, Headers}, same as for HEAD requests 7b60ae0 (let me know if you'd like to keep current {ok, Status, Headers, Ref} behaviour).

Since everyone likes other behaviour I'll make PR to fix it.

**Comment by benoitc** [comment]
@lexmag +1 thanks a lot :)
