### ISSUE TITLE
Connections are not checked in

### ISSUE THREAD

**Issue by ppikula** [benoitc/hackney#160]
I was using the latest version from the master branch (71d67840d097009e).
When I do more request than  the default  pool size  > 50 then the request function
freezes. I found out that the socket is not returned to the pool. I think that 
this code path https://github.com/benoitc/hackney/blob/master/src/hackney_client/hackney_response.erl#L54 
doesn't checkin socket to the pool.   

To reproduce issue extend  `get_request` test in the `hackney_integration_tests.erl` file as follows
(assuming pool size is 50, it should freeze at 51th request):

```erlang
get_request(_) ->
    lists:foreach(fun(_) ->
                          URL = <<"http://localhost:8000/get">>,
                          {ok, StatusCode, _, _} = hackney:request(get, URL, [], <<>>, []),
                          ?_assertEqual(200, StatusCode)
                  end, lists:seq(1,100)).

```

**Comment by benoitc** [comment]
It's expected. you should read the body or skip it using `hackney:skip_body/1` to release the request. If you only want to get the status doing an head request may be the easiest solution though (if your server handle it correctly).

**Comment by benoitc** [comment]
to complete the answer, the socket won't be return if you don't read it until the end. This per design in HTTP. This is why it needs to be read. 

Hope I answered to your question. Let me know.

**Comment by ppikula** [comment]
Thanks for quick reply and sorry for not RTFM. I was using dmitriid/neo4j-erlang and I 
was not able to create more than 50 nodes, so probably the library don't read/skip body in every case.

**Comment by benoitc** [comment]
@ppikula dunno. I actually have one application doing more than 500K calls. Are you sure it's not due to the limitation in the pool? 

In default config you can set it using ` {max_connections, N}` where N is the number of concurrent connections you want to have. One another way to scale it is also using a worker system each using its own pool if you can pass a pool to neo4j-erlang . Let me know.

**Comment by ppikula** [comment]
Yes, It was neo4j-erlang fault. I've added `hackney:skip_body` in that line: https://github.com/dmitriid/neo4j-erlang/blob/master/src/neo4j.erl#L1388 and it is working now.  

Thanks for helping me figuring it out !
