### ISSUE TITLE
Hackney freezes the client process after 150s

### ISSUE THREAD

**Issue by acarstoiu** [benoitc/hackney#163]
Hello,

this one was _very_ annoying and time consuming... It's about the `hackney:request/5` function that is called **without** opting for the default pool by putting `{pool, default}` among the options.

If the remote party (i.e. the HTTP server) is down, _hackney_ returns consistently for about 150s `econnrefused`. That's fine, but as the client keeps retrying the HTTP request every 3 seconds, the 51st attempt simply makes it hang awaiting for an answer -- of course, enforcing a timeout would help it crash instead of freezing, just pick your poison :unamused:
I've noticed that _150000_ is the default value of the `timeout` environment setting for connections in a pool, except that no pool is used in this case.

Fortunately, if the client enables the default pool, then the calls do _not_ hang anymore after 150s :sweat_smile:
Thanks for looking into this.

**Comment by benoitc** [comment]
You can set the `connect_timeout` and `recv_timeout` already in the request, what do you need exactly?

**Comment by acarstoiu** [comment]
I did that, they are both at 5000 (ms). Still, when no connection pool is used and the target server is down, after trying repeatedly for 150s to connect to it, _hackney_ freezes upon the next attempted request.

I reported the problem in order to save other people's time and nerves. I'm not even using _hackney_ directly and I already found a workaround (luckily, I can modify the Erlang application that employs _hackney_ so that it enables the default pool upon every request).

**Comment by benoitc** [comment]
So the problem you have is when you're trying to make a new request in the pool after 50 requests that timeouted?

**Comment by acarstoiu** [comment]
Yes, except that all are **without** the pool. With the pool enabled, no such problem occurs.
(Also, the error is `econnrefused`.)

**Comment by benoitc** [comment]
I don't understand then. Hackney don't try to reconnect at all. What do you mean by freezing? Do you have any code that could help me to reproduce?

> btw by default hackney is using a pool except except if you tell it to not to in the env.

**Comment by acarstoiu** [comment]
[my code] ----> [other app] ---> [hackney] - - - - - -\ . . . [HTTP server]
It is [my code] that keeps retrying. And the [documentation](https://github.com/benoitc/hackney#use-the-default-pool) implies otherwise (i.e. no pool is used if not explicitly stated).
Anyway, after a day of testing, I think you can trust me that there is a difference in behaviour between sending the `{pool, default}` option and not sending it. At least in version _1.0.2_, I forgot to say.

**Comment by benoitc** [comment]
This is not I don't trust you, but to understand the issue which wasn't clear at the beginning ;)

Can you try with the environment settings `use_default_pool` set to False for hackney and let me know ?

**Comment by benoitc** [comment]
The new [hackney_trace](https://github.com/benoitc/hackney/blob/master/doc/hackney_trace.md) module may help to figure what is happening. Can you eventually run it on your own and send me trace?

Here is an example of its usage:
https://www.friendpaste.com/2FviEh6jieAyYwfDZGVwOn

Let me know.

**Comment by acarstoiu** [comment]
Sorry for the silence. As soon as I find some time I will try it, most probably tomorrow.
Thank you.

**Comment by benoitc** [comment]
any news?

**Comment by benoitc** [comment]
The pool have been improved to make sure the connections are correctly closed in the poo, I failed to reproduce. Closing that issue.

If there is anything new to add please feel free to ask me to reopen the issue.
