### ISSUE TITLE
ssl_verify_hostname dependency

### ISSUE THREAD

**Issue by ln5** [benoitc/hackney#165]
benoitc/ssl_verify_hostname is behind its upstream, deadtrickster/ssl_verify_hostname.erl. I'm specifically interested in 640527bfabe656f9522a1116499e0de024084603.

I don't know the reason for hockney to not depend directly on deadtrickster/ssl_verify_hostname.erl. Is it still valid?

**Comment by benoitc** [comment]
For the hackney project i prefer to rely on repositories under my repo so I make sure they will always be available and I can support the code, which is the only reason of this dependency path :)
