### ISSUE TITLE
How can i do [curl -i "http://localhost:8090/?echo=saymyname"] by hackey?

### ISSUE THREAD

**Issue by dcy** [benoitc/hackney#172]
I want to do this: curl -i "http://localhost:8090/?echo=saymyname"
How can i do this by hackney, i tried to set Payload to <<"echo=saymyname">> or <<"{\"echo\":\"saymyname\"}">>, but not work:
    Method = get,
    URL = <<"http://localhost:8090">>,
    Headers = [],
    %Payload = erlang:list_to_binary(util:urlencode([{echo, "saymyname"}])),
    Payload = jsx:encode([{<<"echo">>, <<"saymyname">>}]),
    %Payload = <<>>,
    Options = [{pool, default}],
    {ok, StatusCode, RespHeaders, ClientRef} = hackney:request(Method, URL,
                                                               Headers, Payload,
                                                               Options),

**Comment by edgurgel** [comment]
Maybe: `URL = <<"http://localhost:8090?echo=saymyname">>,`

**Comment by benoitc** [comment]
exactly. You can also use `hackney_url:make_url`

**Comment by benoitc** [comment]
@dcy did we answer to your question?

**Comment by dcy** [comment]
Thanks! it works for me.
