### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by gilv** [benoitc/hackney#174]
I guess i am asking something obvious,
I downloaded source of Hackney and build it with make... all was great and successful
Now, I started a new Erlang project in Eclipse, and wrote some .erl file with few methods..
I can run my file in Eclipse without problems, but i can't use Hackney, for example hackney:start() doesn't work.
I tried to copy all ebin files from Hackney to my project and this time i got an exception
hackney:start().
** exception error: no case clause matching 
                    {error,{"no such file or directory","idna.app"}}
     in function  lists:all/2 (lists.erl, line 1211)
     in call from hackney_app:ensure_deps_started/0 (src/hackney_app/hackney_app.erl, line 33)
     in call from hackney:start/0 (src/hackney_client/hackney.erl, line 56)

So what i missed? how to use Hackney in some project?

Thanks a lot

**Comment by edgurgel** [comment]
You will probably need to copy the files on the `ebin` directory of each project on `deps/`. I would suggest you to use rebar to compile your project or find some plugin on Eclipse that knows how to use rebar.

**Comment by benoitc** [comment]
you need to put the deps in ther ERL_LIBS path so  they can be found.

Unfortunately I am not a user of eclipse, but if you're using erlide this link should help you to solve your issue:
http://stackoverflow.com/questions/15862004/how-to-add-dependency-path-in-erlide

**Comment by benoitc** [comment]
@gilv did we answered to your question?

**Comment by benoitc** [comment]
no feedback since. closing the issue.

**Comment by gilv** [comment]
Thanks guys. it resolved it.
