### ISSUE TITLE
won't encode special character in http get url path

### ISSUE THREAD

**Issue by linbo** [benoitc/hackney#176]
Hi,

I have an restful server with an url like this:

```
http://host:port/id/name:107/?type=FS
```

Since there is an special character colon in the path, I've checked code,  find those codes in hackney.erl

```
request(Method, #hackney_url{}=URL0, Headers, Body, Options0) ->
    %% normalize the url encoding
    URL = hackney_url:normalize(URL0),
```

Actually, I won't wan't encode colon in URL, but maybe in query parameters, but the code seems encode all the URL.

If I use httpc:get, looks working fine.

**Comment by benoitc** [comment]
mmm Is this a valid syntax though? Hackney is reusing the algorithm you can find in chrome. I will check the spec anyway.
