### ISSUE TITLE
Support to bind local ip for transport

### ISSUE THREAD

**Issue by kostya** [benoitc/hackney#181]
seems this is an option {ip, inet:ip_address()} for gen_tcp:connect
http://erlang.org/doc/man/gen_tcp.html

**Comment by benoitc** [comment]
this option is available in latest master.

**Comment by X4lldux** [comment]
How to use it then?
I tried to pass {ip, inet:ip_address()} using `connect_options` in `hackney:request` but that didn't work out.

**Comment by benoitc** [comment]
hrm sorry I closed it too fast.  Indeed the option isn't exposed yet:
https://github.com/benoitc/hackney/blob/master/src/socket/hackney_tcp_transport.erl#L30-L31

 Will fix that in the coming release.
