### ISSUE TITLE
Add an option to return the body immediately, rather than a ref

### ISSUE THREAD

**Issue by rlipscombe** [benoitc/hackney#184]
For simple REST-type calls, it'd be useful if there was an option I could pass that would read the entire response body and return it instead of the ref usually returned.

**Comment by benoitc** [comment]
I added the option [with_body] to do it. It will be available in next release:

    2> hackney:get("https://friendpaste.com", [], <<>>, [with_body]).
    {ok,200,
        [{<<"Server">>,<<"nginx/0.7.62">>},
         {<<"Date">>,<<"Thu, 25 Jun 2015 13:48:27 GMT">>},
         {<<"Content-Type">>,<<"text/html; charset=utf-8">>},
         {<<"Transfer-Encoding">>,<<"chunked">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Set-Cookie">>,
          <<"FRIENDPASTE_SID=16555235843a2c686b0acc1708bb0938b55505b1;
    expires=Thu, 0"...>>},
         {<<"Access-Control-Allow-Origin">>,<<"None">>},
         {<<"Access-Control-Allow-Credentials">>,<<"true">>},
         {<<"Access-Control-Allow-Methods">>,
          <<"POST, GET, PUT, DELETE, OPTIONS">>},
         {<<"Access-Control-Allow-Headers">>,
          <<"X-Requested-With, X-HTTP-Method-Override, Content-Type, "...>>},
         {<<"Access-Control-Max-Age">>,<<"86400">>}],
        <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta
    charset=\"utf-8\"/>\n    <title>Friendpaste - Welcome"...>>}
