### ISSUE TITLE
Add Option to Filter Dangerous IP Addresses

### ISSUE THREAD

**Issue by benmmurphy** [benoitc/hackney#189]
Sometimes you need to make requests to URLs that are supplied by users. However, bad things can happen if you make connections to localhost/private network ip addresses/special multicast addresses. Because of DNS time-to-use time-to-check issues and support for SSL/VHosts it is not possible for a client to check if a hostname resolves to a safe ip address before passing it into hackney:request().

http://www.agarri.fr/docs/AppSecEU15-Server_side_browsing_considered_harmful.pdf

For example:

    {ok, Addrs} = inet:getaddrs(Url#hackney_url.host, inet),
    assertSafeAddresses(Addrs),
    hackney:request(Url)

but in :request method inet:getaddrs is called again and might return a different response.

or if you do:

    {ok, Addrs} = inet:getaddrs(Url#hackney_url.host, inet),
    assertSafeAddresses(Addrs),
    hackney:request(Url#hackney_url{host = hd(Addrs)})

this breaks vhosting and ssl verification (and presumably breaks when proxies are involved. but it will be difficult for hackney to protect you from bad ip addresses when proxies are involved)

i'm guessing with the current api you could do:

    Host = Url#hackney_url.host,
    {ok, Addrs} = inet:getaddrs(Host, inet),
    assertSafeAddresses(Addrs),
    hackney:request(get, Url#hackney_url{host = hd(Addrs)}, [{<<"Host">>, Host}])

which would still work with vhosting but would break ssl. which is probably enough for some peoples use cases.

however, it would be nice if you could do something like:

    Filter = fun(IPAddress) ->
      is_safe(IPAddress)
    end,

    request(get, Url, [], <<>>,[{ip_filter, Filter}])

the only problem with this is it doesn't work correctly with proxies. however, i don't think it is possible to correctly filter ip addresses when dealing with upstream proxies + ssl.

**Comment by benoitc** [comment]
Hrm the link provided doesn't help much when it's about fixing the issue :) 

So to be clear you want a way to pass an Hook used to blacklist IPs based on the URL resolving?

**Comment by benmmurphy** [comment]
exactly

**Comment by benoitc** [comment]
`hackney:request/{1,5}` accept a full `#hackney_url{}` record. Instead of having a custom hook, I think a better solution would be parsing first the url using `hackney_url` and then filter it if needed or not. So we can keep the code simple. 

I will be happy to revisit it if needed but closing it for now as "won't fix". Thanks for the report anyway.
