### ISSUE TITLE
no case clause matching: {:error, :badarg}

### ISSUE THREAD

**Issue by AntonFagerberg** [benoitc/hackney#191]
I'm load testing a system I've built in Elixir which is using Hackney to send requests. The problem is that sometimes (yes, unfortunately sometimes) when I crank up the number of requests executed concurrently I get a matching error which seems to happen because of a missing case clause inside Hackney:

```
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, :badarg}
        (hackney) src/hackney_client/hackney_response.erl:74: :hackney_response.wait_status/1
        (hackney) src/hackney_client/hackney.erl:357: :hackney.send_request/2
```

I'm afraid I don't have any code in which I can replicate this issue, but please tell me if there is any additional information I can provide.

Here's the Hackney code which seems to fail: https://github.com/benoitc/hackney/blob/master/src/hackney_client/hackney_response.erl#L74

**Comment by zweizeichen** [comment]
Yup - same problem here when increasing the number of requests/s. @AntonFagerberg Are you sure  this is a problem of Hackney and not the server we're querying?

**Comment by benoitc** [comment]
is there any url I could test on? Or does it happen on any server?

**Comment by zweizeichen** [comment]
Just set up a simple test and ran 10k parallel requests with HTTPoison and a local Cauldron server. Everything ran just fine. I then introduced random response delays on the server up to 10 seconds and it still worked flawlessly for 1k requests, I'm getting the error more than once per second when I'm running at around 150 requests per second for a while in a real-world scenario (public API server, nginx 1.2 I think). Maybe it's related to some connections hanging or something like that. It only happens when I query the 'real' server.

**Comment by AntonFagerberg** [comment]
@zweizeichen No, not sure if it's Hackney or a bad behaving web server. I have tried to recreate this bug in every way I can think of today but I've been unable to do so...

**Comment by benoitc** [comment]
me either. And I tried hard.... can you try the latest master?

**Comment by unitymind** [comment]
Similar issue, but different pattern matching case:

```
(CaseClauseError) no case clause matching: {:error, :bad_request}
            (hackney) src/hackney_client/hackney_response.erl:74: :hackney_response.wait_status/1
            (hackney) src/hackney_client/hackney.erl:357: :hackney.send_request/2
```

Reproducing: trying to get request using **http** schema in url (e.g. http://127.0.0.1:2376) where is 2375 port is TLS/SSL. If change url to **https** schema - works as expected.

Sometimes no information about http or https schema on the end-port. The best solution: transparency switch from http to https. But just handle this case in pattern matching would be great too :)

**Comment by benoitc** [comment]
@unitymind thanks for the tests. The error should happen during handshake then, I will have a look on ho to catch the error in the coming release.

**Comment by unitymind** [comment]
Currently I am use workaround:

```
try do
...
rescue
  e in CaseClauseError ->
    case e do
      %CaseClauseError{ term: { :error, :bad_request } } ->
        check_base_url(url |> String.replace("http://", "https://"))
    end
end

recursive call with schema changing. 

Think so the most non-destructive solution is return { :error, %HTTPoison.Error {} }

**Comment by benoitc** [comment]
Thanks :) The error is happening on connect, with the new connection api it
will be easier to fix it. New release is planned this week. it will be
partly based on the `hackney_socks` release.

**Comment by unitymind** [comment]
Thanks for your efforts! )

**Comment by cwc** [comment]
Any update on this?

**Comment by benoitc** [comment]
@cwc a nrew release of hackney will land on next monday.
