### ISSUE TITLE
error: "unknown ca" when talking to Twilio's API

### ISSUE THREAD

**Issue by JonahBraun** [benoitc/hackney#196]
Erlang 17.5 on MacOSX.

Trying to GET https://api.twilio.com/ results in:
 12:36:48.062 [error] SSL: :certify: ssl_handshake.erl:1401:Fatal error: unknown ca

I've tried the latest master of hackney. Also, regenerated ca-bundle.crt w/ the provided perl script. Is ca-bundle.crt read at runtime or is it compiled in?

Using curl and Firefox on the same system to talk to Twilio work fine.

Please let me know I should provide any other information. Thanks!

**Comment by benoitc** [comment]
The certificate used by twillio is invalid:

![screen shot 2015-06-19 at 21 27 33](https://cloud.githubusercontent.com/assets/14498/8261356/1f01e474-16ca-11e5-992b-e93252365c56.png)

To bypass validation you can use the `insecure` setting:

    1> application:ensure_all_started(hackney).
    {ok,[crypto,asn1,public_key,ssl,idna,hackney]}
    2>  hackney:get("https://api.twillio.com").

    =ERROR REPORT==== 19-Jun-2015::21:26:56 ===
    SSL: certify: ssl_handshake.erl:1405:Fatal error: handshake failure
    {error,{tls_alert,"handshake failure"}}
    3>  hackney:get("https://api.twillio.com", [], <<>>, [insecure]).
    {ok,301,
        [{<<"Content-Type">>,<<"text/html">>},
         {<<"Date">>,<<"Fri, 19 Jun 2015 19:29:26 GMT">>},
         {<<"Location">>,<<"https://www.twilio.com/">>},
         {<<"Server">>,<<"nginx">>},
         {<<"Strict-Transport-Security">>,<<"max-age=15768000">>},
         {<<"X-Shenanigans">>,<<"none">>},
         {<<"Content-Length">>,<<"178">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Set-Cookie">>,
          <<"visid_incap_260724=sMbyXRI4Sr+XlibSBV4ojJVthFUAAAAAQUIPAAAAA"...>>},
         {<<"Set-Cookie">>,
          <<"nlbi_260724=J8xbbiBHkCKAqSnBJqATpgAAAACMeIypFnF/JsKOSkFL"...>>},
         {<<"Set-Cookie">>,
          <<"incap_ses_236_260724=S9O4fvtNZzHA8hw/V3FGA5VthFUAAAA"...>>},
         {<<"X-Iinfo">>,
          <<"1-5035704-5035722 NNNN CT(3 22 0) RT(14347421652"...>>},
         {<<"X-CDN">>,<<"Incapsula">>}],
        #Ref<0.0.0.106>}

Curl tell me the same thing there though:

    [hackney] curl https://api.twillio.com                                                             21:30:45  ☁  master ☂ 𝝙 ⚡ 
    curl: (60) SSL certificate problem: Invalid certificate chain
    More details here: http://curl.haxx.se/docs/sslcerts.html

maybe you have some certificates already instaleld on your machine?

**Comment by JonahBraun** [comment]
Sorry, it looks like Twillio redirects in certain circumstances. This URL should work: https://api.twilio.com/2010-04-01/Accounts/

Thanks for the tip on using `insecure` as a temporary fix. I'm happy to try any troubleshooting steps you recommend. Thanks!

cURL:
```bash
#⚡  curl https://api.twilio.com/2010-04-01/Accounts/
<?xml version='1.0' encoding='UTF-8'?>
<TwilioResponse><RestException><Code>20003</Code><Detail>Your AccountSid or AuthToken was incorrect.</Detail><Message>Authentication Error - No credentials provided</Message><MoreInfo>https://www.twilio.com/docs/errors/20003</MoreInfo><Status>401</Status></RestException></TwilioResponse>
```

Elixir (calling the latest Hackney):
```elixir
iex(1)> :hackney.get("https://api.twilio.com/2010-04-01/Accounts/")

16:23:40.635 [error] SSL: :certify: ssl_handshake.erl:1401:Fatal error: unknown ca

{:error, {:tls_alert, 'unknown ca'}}
```

With :insecure:
```elixir
iex(3)> :hackney.get("https://api.twilio.com/2010-04-01/Accounts/", [], "", [:insecure])
{:ok, 401,
 [{"Access-Control-Allow-Credentials", "true"},
  {"Access-Control-Allow-Headers",
   "Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since"},
  {"Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS"},
  {"Access-Control-Allow-Origin", "*"},
  {"Access-Control-Expose-Headers", "ETag"},
  {"Content-Type", "application/xml"},
  {"Date", "Sun, 21 Jun 2015 22:29:30 GMT"},
  {"WWW-Authenticate", "Basic realm=\"Twilio API\""},
  {"X-Powered-By", "AT-5000"}, {"X-Shenanigans", "none"},
  {"Content-Length", "327"}, {"Connection", "keep-alive"}],
 #Reference<0.0.0.1481>}
```

Cert in Chrome:
![monosnap 2015-06-21 16-42-13](https://cloud.githubusercontent.com/assets/611339/8273659/8b31c680-1834-11e5-8376-2cf7c4404839.png)

**Comment by benoitc** [comment]
@JonahBraun thanks!

Though I am not sure yet why it is happening. I have updated the CA (even reusing the one from curl) and tried miscellaneous options but it didn't change anything. Working on it...

**Comment by deadtrickster** [comment]
maybe intermediate certificate is missing? so erlang unable to reconstruct the chain?

**Comment by ericmj** [comment]
Erlang only check against the root certificate in the chain. If you want to stop traversing the chain at a trusted intermediate certificates you need to use the `partial_chain` option.

**Comment by benmmurphy** [comment]
I believe this is because erlang doesn't support SNI. Apparently, support has been merged into the master branch and will be released in r18.

**Comment by ericmj** [comment]
I don't think SNI support is required here, but I am not 100% sure. I am certain that many domains break when using the CA store hackney uses without using the `partial_chain` option.

**Comment by benoitc** [comment]
@ericmj any example of usage of `partial_chain` in mind?

**Comment by ericmj** [comment]
Only elixir code I am afraid: https://github.com/hexpm/hex/blob/master/lib/hex/api.ex#L59-L81.

It works but I don't know if it's correct. I haven't had anyone that know erlang ssl internals take a look it. It is all very poorly documented.

**Comment by benoitc** [comment]
I updated the PEMS to the one use in OSX (via keychain). It is now working. 

Notes: 
- I didn't have success with partial chains. Somehow it wasn't used at all.
- CAs from stock curl are not enough

**Comment by ericmj** [comment]
I am afraid it is still broken. The reason it works with OSX's keychain is probably because it includes the root certificate of Twilio's certificate chain and curl's CA store only includes an intermediate certificate. The only way to get a fully working verification is to use `partial_chain` unless you use CA store which only have root certificates (which I doubt OSX's have).

curl and firefox use the same CA store and I can access https://api.twilio.com from both so it's not an issues with the store.

**Comment by benoitc** [comment]
Though I don't have any success using `partial_chain`, the function is not called at all, cf the thread on the mailing-list, and not sure why. Are you sure the function is called in the code above? If someone can give me a working example it would help.

I am not sure handling automatically partial chains is a good idea anyway, at list its usage should be explicit since in normal case you should trust the full chain...

**Comment by benoitc** [comment]
@ericmj also partial_chain is not available in R16 so it's not a solution for 1.1x. I will try (if any success with it) to have it in 2.x. Let's do the quick fix first.

**Comment by benoitc** [comment]
reopened the issue to see if we can achieved to have a better solution in 2.x

**Comment by ericmj** [comment]
I am sure the function is being called, I just tested it for Hex. Can't give you more examples than the one above, sorry. I will take a look at the code in the ML later today.

By trusting a certificate you have implied trust for all certificates below. With PKIX you don't have trust everything in the chain, that's the point of it. What makes an explicitly trusted intermediate certificate less trustworthy because its signer is not in the CA store? Including all root certificates in the store is actually less safe because peer certificates should definitely not be signed by them directly.

**Comment by benoitc** [comment]
well right. But I'm not including all the certificates, only the one trusted by Apple in Safari. 

I will try to play more with this partial_chain feature.

**Comment by ericmj** [comment]
There's a big chance that Apple includes many intermediates without their corresponding roots as well. I don't see why Safari would be different than every other HTTPS client. It's just chance that Apple happen to include Twilio's root.

**Comment by benoitc** [comment]
@ericmj Well it's still odd Apple have it. But anyway I agree that a better solution should be found. 

In term of action I see the following:
- how to handle partial_chain in version < 17 (for current 1.x version). A validate_fun may work but it will need some work. Maybe it could just be skipped for now in this version
- make partial_chain working... I don't understand why the function is not used in my code...
- decide about the root certificate policy. Like the one in chromium: https://www.chromium.org/Home/chromium-security/root-ca-policy

Any other thoughts?

**Comment by ericmj** [comment]
partial_chain was added around ~17.3, maybe that's why it didn't work for you? A specific root certificate policy is not needed if you use one of the stores linked from chromiums policy page and you update the store reasonably often so revoked certificates are updated for hackney for as well. curl is using mozilla's store for example.

**Comment by benoitc** [comment]
@ericmj i tested it on 17.5.6 and 18 with same results so I am not sure yet. I am probably doing something wrong. Will put more cycles on it over the coming week.

As for the certificate I agree. I will probably continue to generate them from apple store and add the needed makefile line for all. It will still possible to use the mozilla store.

**Comment by benoitc** [comment]
thanks all for the useful feedback :)
