### ISSUE TITLE
Maintain our list of available trusted root certificates?

### ISSUE THREAD

**Issue by benoitc** [benoitc/hackney#200]
Hackney used to build the root certificates file in PEM format using the data coming from Mozilla and the script from curl.  But it appears this list isn't enough for some domain and #196 has been fixed by extracting the trusted certificates from the Apple System Keychain. The full list is available there: https://support.apple.com/en-us/HT202858 

Hackney may need have its own policy to trust some certificates. But how to maintain the list? The risk of maintaining your own list is high... Is there any better way to do it? Feedback is welcome.

**Comment by deadtrickster** [comment]
I think it depends on usage. For example if I'm building API client I will be using certificates provided by vendor itself (like here https://github.com/stripe/stripe-ruby/tree/master/lib/data). 
For general case I believe using system-wide repository can be a good idea.

**Comment by benoitc** [comment]
unfortunately not all vendors make them accessible. For example on osx they
have to be exported from keychain. Thinking more of it you should have the
same experience using hackney on each platform wherue Erlang is supported.
It imply then to ship the same default store. The question is more how to
build it now.

**Comment by benoitc** [comment]
for now let just use the mozilla list now that partial certificates are handled.
