### ISSUE TITLE
Error compile

### ISSUE THREAD

**Issue by Kozlov-V** [benoitc/hackney#201]
==> hackney (compile)
Dependency not available: idna-1.0.2 (undefined)
Dependency not available: ssl_verify_hostname-1.0.5 (undefined)

**Comment by benoitc** [comment]
I don't reproduce it. What's your command line?

**Comment by benoitc** [comment]
So this error was due to the new usage of rebar3  which I now advise. 2.0 will require it.

**Comment by benoitc** [comment]
thanks for the feedback anyway... I would have forgotten :)

**Comment by Kozlov-V** [comment]
@benoitc Benoit, thank you!
