### ISSUE TITLE
Discrepancy between docs and implementation re: `use_default_pool`

### ISSUE THREAD

**Issue by jasonwebster** [benoitc/hackney#203]
The README implies that in order to use the default pool, you must first set the application env key `use_default_pool` to true: https://github.com/benoitc/hackney/blob/master/README.md#use-the-default-pool

However, in the code, the default is true:
https://github.com/benoitc/hackney/blob/b5282d1e911fc5b8b70d47ac6bc7f577284a2591/src/hackney_connect/hackney_connect.erl#L266-L272

And the .app file doesn't specify it at all: https://github.com/benoitc/hackney/blob/master/src/hackney.app.src#L18

I'd just open a PR fixing the inconsistency, but I'm unsure as to what the intended default behaviour actually is.

**Comment by benoitc** [comment]
Thanks!
