### ISSUE TITLE
Don't use infinity as default timeout

### ISSUE THREAD

**Issue by RJ** [benoitc/hackney#219]
There is a default 'infinity' `recv_timeout` in [hackney:request](https://github.com/benoitc/hackney/blob/master/src/hackney_client/hackney.erl#L245)

infinity makes a poor default, imo.

**Comment by edgurgel** [comment]
Interesting that I got a similar comment on HTTPoison https://github.com/edgurgel/httpoison/issues/64

**Comment by benoitc** [comment]
It's now set to 5s :) Not sure right now what is the best value for it.

**Comment by benoitc** [comment]
Also in the next version it shouldn't freeze anymore the pool.

**Comment by RJ** [comment]
@benoitc great :)
did you make another change related to the pool freezing, or are you just referring to the default timeout?

for the record, we started seeing connections (to s3) hanging indefinitely after upgrading from 0.13.0 to 1.1.0

**Comment by benoitc** [comment]
Pool locking will be handled in  the next release. Basically there won't be
any locking or freezing waiting for a connection to be released. Instead we
will only make sure to maintain a max of reused connection with a maximum
time given to a connection to be kept alive. This version will be available
sometimes this week.
