### ISSUE TITLE
Custom client certificate and CA

### ISSUE THREAD

**Issue by zyro** [benoitc/hackney#225]
I'm integrating an external service into my application and due to constraints from the 3rd party I'll have to use:
* A custom client certificate, similar to `cURL`'s `-E` or `--cert` option.
* A custom CA, similar to `cURL`'s `--cacert` option.

Is there a way I can specify these? Ideally this would only be for requests going to this remote host, of course.

**Comment by benoitc** [comment]
yea you can pass any ssl options at the request using the ssl_options
setting. it.accept the list of properties described in the ssl module.

**Comment by benoitc** [comment]
@zyro did it answer to your question?

**Comment by zyro** [comment]
Yep, looks like exactly what I need. Thanks!
