### ISSUE TITLE
Allow force 303 redirects if the method is not a POST

### ISSUE THREAD

**Issue by tnt-dev** [benoitc/hackney#229]
Now non-POST 303 redirects are forbidden and client gets `invalid_redirection` error. Maybe we can allow this when `force_redirect` is enabled?

**Comment by benoitc** [comment]
What would be your use case for it?

**Comment by benoitc** [comment]
I mean it doesn't seems legal to get a 303 for anything but post. But we can add it for sure. Just curious when it happen, I never encountered this issue

**Comment by tnt-dev** [comment]
In my code I make requests to different URLs and one of them returns 303 after GET. It's not my server and I can't change something on it but I have to check its state and it is problem for me when I get `{error, ...}`. So it would be convenient to have a way to handle this situation as normal.

**Comment by benoitc** [comment]
according the RFC 7231:

>  A 303 response to a GET request indicates that the origin server does  not have a representation of the target resource that can be  transferred by the server over HTTP.  However, the Location field  value refers to a resource that is descriptive of the target  resource, such that making a retrieval request on that other resource  might result in a representation that is useful to recipients without  implying that it represents the original target resource. 

I am not sure hackney should automatically redirect to it until it is forced. I propose the following change:

1. By default instead of returning `{error, {invalid redirection, Resp}}`, we should instead return a `{see_other, Location, Body}`
2. If the optiob `force_redirect` is set to `true` then do the redirection if it happens.

Thoughts?

**Comment by tnt-dev** [comment]
I think it's a good variant. This way we can control behavior and handle errors when required.

**Comment by tnt-dev** [comment]
Closing this since #307 was merged. Thanks!
