### ISSUE TITLE
Hackney 1.3.2 is not on Hex.pm

### ISSUE THREAD

**Issue by eproxus** [benoitc/hackney#234]
Sorry if this is something you already have planned to do, I just noticed that Hackney 1.3.2 is [missing on Hex.pm](https://hex.pm/packages/hackney).

**Comment by benoitc** [comment]
i will have a look at it. Thanks for the notice

**Comment by edgurgel** [comment]
I was sending PRs for each version: https://github.com/hexpm/community/pulls?q=is:pr+author:edgurgel+is:closed

We can move the ownership to @benoitc if wanted. I'm pretty sure @ericmj and @MSch would love :)

I supposed https://github.com/hexpm/rebar3_hex is totally capable of dealing with this from the erlang side.

**Comment by benoitc** [comment]
sorry missed that ticket... @edgurgel could it be done directly from the hackney repo? I am fine if you're doing it for now. Full rebar3 support will come in next major version. Which should come very soon now.

**Comment by edgurgel** [comment]
It seams totally doable if we use rebar3 and rebar3_hex. We can set this up for the next major version :+1:

**Comment by benoitc** [comment]
Good. Let's keep open this ticket as a reminder. 

@edgurgel can you in the mean time send the last stable version to hex? would be good to have it since it solves many issues experimented by some users.

**Comment by edgurgel** [comment]
The last one was already sent by someone else and it was already published: https://hex.pm/packages/hackney/1.3.2

**Comment by benoitc** [comment]
pretty cool :)
