### ISSUE TITLE
add an API to skip the body asynchronously

### ISSUE THREAD

**Issue by benoitc** [benoitc/hackney#235]
While answering to #233 it came to my mind that we could have an option to skip the body asynchronously. The following can be added to the API:

- add the `skip_body` option to a request. It will read the full body and discard it asynchronously. The request will only return `{ok, Status, Headers}` like an `HEAD` request.
- add `hackney:skip_body/2` supporting an `async` option to read the full body and release the socket asynchronously.

**Comment by edgurgel** [comment]
:+1:
