### ISSUE TITLE
hackney_http_proxy:connect_proxy/5 alternative.

### ISSUE THREAD

**Issue by cs-codesocial** [benoitc/hackney#239]
Hey benoitc,

"hackney_http_proxy" seems to be missing/removed. 
Is there any other way to establish connection references which can be reused in
subsequent serial requests over a proxy?

Thanks

**Comment by benoitc** [comment]
`hackney_http_connect`is replacing it. What are you trying to do exactly?

**Comment by benoitc** [comment]
did it answer to your question?

**Comment by cs-codesocial** [comment]
Hey benoitc,

apologies for the late reply, been a bit busy over here.
Yes, this answers it, was just a little confused as the readme mentioned a non-existing function.
Your pointer + looking at the sources got me sorted out though.

Thanks again

**Comment by benoitc** [comment]
@cs-codesocial np, thanks for the feedback :) The README will be edited ASAP. There will be be a lot of change sin coming 2.0 related to #243 .


Closing it and keeping a link in #243
