### ISSUE TITLE
Does hackney use ets table per connection?

### ISSUE THREAD

**Issue by shankardevy** [benoitc/hackney#250]
I am using ibrowse at the moment and it works fine. However, I have hit the ets table limit since ibrowse uses 1 ets table per server/port combination. see https://github.com/cmullaparthi/ibrowse/issues/135

how does hackney approach this issue? does it also use ets table and have similar limitation? My requirement is to have GET requests to several thousands of urls/min (most of them are unique tlds).(about 5000/min for now and will increase in future)

**Comment by benoitc** [comment]
Sorry for the late answer.

Hackney in its current version and the next one is only using 1 ETS per pool of sockets. Each new endpoint is added to the pool ETS and you will never have more than the max_connections in a pool. Most of the time you won't need more than a pool, but when you need more concurrency it can be useful to share your connections between different pools.

Hope it answers to your question.

**Comment by shankardevy** [comment]
thanks @benoitc for your reply. It's a quick reply, indeed.

For my requirement of fetching snapshots from IP camera, I would need at least 5000 concurrent calls to different camera (different ip addresses, ports). So in this case, how would hackney's pool behave?

also if you could forgive my naive question, why does ets come into picture here? what kind of information does hackney store in ets and why?  are we caching anything? and what purpose does it serve when each time I request a url, I expect a new image? 

I am sorry if these questions are pretty basic and you expect the users to already know it :-)

**Comment by benoitc** [comment]
The pool is here to cache the sockets connections, ie to keep them alive. If you set the limit to 5000 it will works in current version. Next version will cache more efficiently the connections. You can have a look of the current design here:

http://www.erlang-factory.com/static/upload/media/1394461730695138benoitchesneau.pdf

and the video:

http://www.infoq.com/presentations/erlang-http-connections

Hope it helps.

**Comment by benoitc** [comment]
hopefully the issue has been answered. Closing the ticket then. (if not feel free to contact me directly).
