### ISSUE TITLE
Error evaluating rebar config script

### ISSUE THREAD

**Issue by akeating** [benoitc/hackney#255]
When I attempt to use Timex or Calendar in a new PhoenixFramework app, I see this in my compile output:

```
==> hackney
Error evaluating rebar config script "./rebar.config.script": 30: evaluation failed with reason error:{badmatch,undefined} and stacktrace [{erl_eval,expr,3,[]}]
Any dependency defined in the script won't be available unless you add them to your Mix project
```

It's not clear to me whether this is a bug issue with hackney or configuration issue. Any insights appreciated.

**Comment by zyro** [comment]
I've also seen this same issue. Happens in hackney 1.4.0, does not happen in 1.3.2. All other dependencies, versions, and config are the same.

**Comment by akeating** [comment]
Thanks @zyro. I can confirm that requiring hackney 1.3.2 fixed the problem.

**Comment by benoitc** [comment]
thanks for the ticket. how can i reproduce the error? are you adding dirextly hackmney to your project?
