### ISSUE TITLE
Timeouts when making POST requests to chromedriver

### ISSUE THREAD

**Issue by HashNuke** [benoitc/hackney#256]
Making a POST request to the chrome driver fails. Here are steps to reproduce.

### Requirements

* Install chromedriver (from homebrew if Mac `brew install chromedriver`) or download from http://chromedriver.storage.googleapis.com/index.html?path=2.20/

* Start the chrome driver with `chromedriver --verbose`

### Reproducing the error

The original code is in Elixir, so I'm just pasting it as is.

```elixir
body = Poison.encode! %{desiredCapabilities: %{}}
headers = [{"Content-Type", "text/json"}]
method = :get
url = "http://localhost:9515/session"

{:ok, sc, rh, cr} = :hackney.request(:get, url, headers, body)
{:ok, body} = :hackney.body(cr)
```
The request times out after a long time. Should be useful to pass the `recv_timeout` as `5000` option to debug faster.

Same request is successful with a response when using curl in the command line:
```
$ curl --data "{\"desiredCapabilities\": {}}" --header "Content-type: text/json" http://localhost:9515/session
{"sessionId":"87d6b9cfb5bd2bd1782e65f2b6a30511","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"userDataDir":"/var/folders/96/1sp35x9j2n116stp3gtk3m5w0000gn/T/.org.chromium.Chromium.MBiD8D"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"platform":"Mac OS X","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"46.0.2490.80","webStorageEnabled":true}}
```

Please do let me know if I'm doing something wrong here.

> Original issue on the HTTPoison repo - https://github.com/edgurgel/httpoison/issues/86

**Comment by benoitc** [comment]
@HashNuke you probably want to `post` here. `get` is only able to fetch :)

In erlang:

'''
1> application:ensure_all_started(hackney).
{ok,[idna,mimerl,certifi,hackney]}
2> hackney:post("http://localhost:9515/session", [{<<"Content-Type">>, <<"Application/Json">>}], <
<"{\"desiredCapabilities\": {}}">>).
{ok,200,
    [{<<"Content-Length:242">>,<<>>},
     {<<"Content-Type:application/json; charset=utf-8">>,<<>>},
     {<<"Connection:close">>,<<>>}],
    #Ref<0.0.2.2325>}
3>
'''

**Comment by HashNuke** [comment]
@benoitc thank you ~! facepalm. Sorry didn't notice that I was passing `:get` to hackney. Confirmed that this is a httpoison problem.
