### ISSUE TITLE
System limit reached

### ISSUE THREAD

**Issue by shankardevy** [benoitc/hackney#257]
I am using HTTPoison and hoping that this error comes from hackney, I am creating an issue here.

```
%HTTPoison.Error{id: nil, reason: :system_limit}
```
I am getting the above error after fetching about 3000 unqiue urls for every minute for several hours. What is the system_limit that has been reached and how can I increase it?

Thanks

**Comment by benoitc** [comment]
it's probably the fd limit. try to increase it with ulimit -n

**Comment by mosic** [comment]
Hi @benoitc, thanks for the suggestion (we work on the same project). We tried increasing the limit and we're still seeing `:system_limit` errors after running the application for several hours.

Here is the current configuration we use:

```
$ ulimit -n
10000
```

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 120241
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 10000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 120241
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Any ideas?

**Comment by shankardevy** [comment]
@benoitc could this be a possible bug in hackney similar to this?
http://mail-archives.apache.org/mod_mbox/couchdb-user/201009.mbox/%3CAANLkTinyvMW+Ucg2R-O0jfwP0wpfV5VhivOM8EsMsRLj@mail.gmail.com%3E

I mean is there a possibility that hackney doesn't close a connection properly or something like that? I just throwing some random ideas and would greatly appreciate if you could share your wisdom.

I did a traceback when I got the 'system_limit' error on hackney and this is what I got. (Actually a lot of them but with different Targets)
```
File operation error: system_limit. Target: /home/ubuntu/media/lib/timex-0.19.5/ebin/Elixir.Inspect.Integer.beam. Function: get_file. Process: code_server.'
```

**Comment by benoitc** [comment]
are you always reading the body?

**Comment by shankardevy** [comment]
@benoitc what do mean reading the body? using `response.body` somewhere in the code? I have a few calls that make a post request and doesn't do anything with the response and a few requests where I only read the header value. does it have any effect?

**Comment by benoitc** [comment]
@shankardevy definitely, you need to do something with the response. Or the socket won't be released.

**Comment by shankardevy** [comment]
@benoitc it looks like `HTTPoison` already reads the body of every request
https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L401

However, what I noticed is that it takes about 120-150 seconds to free up an used port. why is it? is that configurable?

```
iex(1)> :erlang.system_info(:port_count)
11
iex(2)> {:ok, _,_,c} = :hackney.get "http://www.google.com"
{:ok, 302,
 [{"Cache-Control", "private"}, {"Content-Type", "text/html; charset=UTF-8"},
  {"Location", "http://www.google.co.in/?gfe_rd=cr&ei=Tq1DVuGeMubI8Af_2LbACw"},
  {"Content-Length", "261"}, {"Date", "Wed, 11 Nov 2015 21:04:14 GMT"},
  {"Server", "GFE/2.0"}], #Reference<0.0.3.1075>}
iex(3)> :erlang.system_info(:port_count)                   
12
iex(4)> :hackney.body c
{:ok,
 "<HTML><HEAD><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF=\"http://www.google.co.in/?gfe_rd=cr&amp;ei=Tq1DVuGeMubI8Af_2LbACw\">here</A>.\r\n</BODY></HTML>\r\n"}
iex(5)> :erlang.system_info(:port_count)
12
####### after about 120-150 seconds ######
iex(48)> :erlang.system_info(:port_count)
11

```

**Comment by benoitc** [comment]
The socket is put in a pool and reused. Maybe you're achieving the maximum sockets there? How can I reproduce it?

**Comment by edgurgel** [comment]
I suggested him to tweak the params to hold connections and also check if it's a good usage of the pool (if every request may be to a different host there's no much need to hold the connection open, I suspect):

https://github.com/edgurgel/httpoison/issues/98#issuecomment-156023267

**Comment by benoitc** [comment]
@edgurgel there is a coming change: https://github.com/benoitc/hackney/compare/new_pool that should improve a lot the pool. I need to plug it to the rest asap. Not until next week i guess though.

**Comment by benoitc** [comment]
supersed by #276 . Thanks all for the feedback :)
