### ISSUE TITLE
Cowboy is always in rebar2 deps

### ISSUE THREAD

**Issue by bitwalker** [benoitc/hackney#259]
See [here](https://github.com/benoitc/hackney/blob/master/rebar.config.script#L25).

It looks to me like you intended to only add cowboy under `TEST`, but it's always in the deps being appended to. This is currently causing a problem in an Elixir project of mine when mix tries to compile hackney and it can't find the cowboy dependency. I've resolved it locally by rolling back to hackney 1.4.4, but I imagine more people will run into this same issue since hackney is so widely used in Elixir libraries.

**Comment by jlouis** [comment]
Does the project work if you remove that line you refer to?

**Comment by bitwalker** [comment]
@jlouis Yes it does

**Comment by jlouis** [comment]
It looks like a fairly easy fix then :)

**Comment by antipax** [comment]
:+1:

**Comment by bitwalker** [comment]
Closing this since the fix was merged. Thanks!
