### ISSUE TITLE
serious memory leak with ssl with default options on R16B03

### ISSUE THREAD

**Issue by brigadier** [benoitc/hackney#269]
`1> hackney:start().`
ok
`2> Url = "https://www.dan.me.uk/torlist/".`
"https://www.dan.me.uk/torlist/"
`3> L = lists:seq(1, 100).`
[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
 23,24,25,26,27,28,29|...]
`4> memory().`
[{total,23401608},
 {processes,5202720},
 {processes_used,5202680},
 **{system,18198888}, %% 18M** 
 {atom,264505},
 {atom_used,258344},
 {binary,1822080},
 {code,6776041},
 {ets,763544}]
`5> lists:foreach(fun(_) -> {ok, Code, _Headers, Client} = hackney:request(get, Url, [], <<>>, [{follow_redirect, true}, {recv_timeout, 90000}]), hackney:close(Client), ok end, L).`
ok
`6> memory().`
[{total,158929704},
 {processes,6451024},
 {processes_used,6451024},
 **{system,152478680}, %% 152M**
 {atom,380409},
 {atom_used,379471},
 {binary,26367504},
 {code,11186241},
 {ets,105714048}]
`7> lists:foreach(fun(_) -> {ok, Code, _Headers, Client} = hackney:request(get, Url, [], <<>>, [{follow_redirect, true}, {recv_timeout, 90000}, {ssl_options, []}]), hackney:close(Client), ok end, L).`
ok
`8> memory().`
[{total,158880824},
 {processes,6402040},
 {processes_used,6402040},
 **{system,152478784}, %% 152M**
 {atom,380409},
 {atom_used,379471},
 {binary,26367608},
 {code,11186241},
 {ets,105714048}]

On Erlang 18.0 there's either no leak, or the leak is less obvious (I'm not sure) - system memory in the same example is 28713664, 31837760, 31861368

upd: it's the ssl_otp_session_cache table which grows, looks like well-known issue in some Erlang versions

**Comment by bradfordw** [comment]
Curious with the release of [18.2 ](http://www.erlang.org/news/97) it mentions one of the fixes being:
 ssl: Add configurable upper limit for session cache.

Curious if that resolves this or not for you; assuming of course that you're able to upgrade OTP.

**Comment by brigadier** [comment]
I fixed the issue on R16B03-1 with running erl with `-ssl session_lifetime 120` and using `{ssl_options, [{reuse_sessions, false}]}`. Cert check is disabled, but in my case it is not needed.

**Comment by benoitc** [comment]
thanks, that is definitely interesting :) I will add it to the readme asap.

**Comment by fp** [comment]
I can confirm that this:
- happens with the latest hackney (1.6.1 and master)
- when running on R16B03-1
- allowing `ssl_otp_cacertificate_db` ETS table to grow out of control (> 150GB of memory)

Specifying `ssl_options, [{reuse_sessions, false}]}` as part of the request `Options` parameter does prevent this ETS table from growing at all.

This does not happen on Erlang 18+, likely because of the limits on this caching that were implemented as part of 18.

**Comment by benoitc** [comment]
I suggest to upgrade to the latest version of Erlang. (anything > 18) . 

Next major version of hackney will remove any version of Erlang < 19, the 1.x branch will only support bug fixes.
