### ISSUE TITLE
rebar.config.script references different version of idna

### ISSUE THREAD

**Issue by rlipscombe** [benoitc/hackney#270]
See https://github.com/ninenines/erlang.mk/issues/471

> It doesn't appear to work correctly, because rebar.config.script still references idna 1.0.2, and it looks like erlang.mk is using rebar 2.x.

**Comment by benoitc** [comment]
fixed. Thanks!

**Comment by rlipscombe** [comment]
Related: https://github.com/benoitc/erlang-idna/issues/10.
