### ISSUE TITLE
Strange behavior with :POST request

### ISSUE THREAD

**Issue by sikanhe** [benoitc/hackney#272]
Hey so it seems like i am hitting some kind of bug with POST request.
In all my other languages, i can successfully make the follow request to the url(should return 403)

https://EXERW3T3UB-dsn.algolia.net/1/indexes/*/queries

but with hackney its returning 404,i think it might have something to do with the * asterisk in the url, because that is only url that has it and the only one thats causing issues with 404.

**Comment by benoitc** [comment]
Right `*` will be url encoded. This issue is similar to #246 . Normally the server should decode it but... I will take about that in next release.

**Comment by sikanhe** [comment]
Is there an immediate fix for this ? I just need to support  "*" badly right now, could you guide me to a workaround ?

**Comment by benoitc** [comment]
@sikanhe new master has now the possibility to set your own path encoding function. Normally servers are supposed to decode path correctly though... Let me know if if it works for you. I will make a new release tomorrow.

**Comment by benoitc** [comment]
addionnaly added the "*" case.

**Comment by sikanhe** [comment]
@benoitc thank you so much!

**Comment by sikanhe** [comment]
Hey I tried out the master branch, it didn't seem to recognize the function I put in as an option at.. So i dug in the code and traced the bug to hackney_url:normalize(Url, Fun), in which the function didnt actually apply to the url, it always uses hackney_url:pathencode/1

https://github.com/benoitc/hackney/blob/master/src/hackney_url.erl#L104

So I forked it and made the change to actually use the function being passed in the argument and submitted a PR https://github.com/benoitc/hackney/pull/306

**Comment by benoitc** [comment]
i merged the pr. sorry for that...
