### ISSUE TITLE
hackney stops sending after 50 requests

### ISSUE THREAD

**Issue by maruks** [benoitc/hackney#274]
if I don't invoke hackney:body(ConnRef)
then hackney stops working after sending 50 requests

is it {max_connections, 50} ?

**Comment by benoitc** [comment]
@maruks you need to release the socket in the current version. Either by reading the body or skipping it. If not the limit of connections will be achieved. This is at least the current behaviour.

**Comment by benoitc** [comment]
closing the issue since it has been answered (at least I will considered the silence as an OK).
