### ISSUE TITLE
new manager to reuse connections

### ISSUE THREAD

**Issue by benoitc** [benoitc/hackney#276]
## Old design

Current version of Hackney is using a classic pool system. Ie. the **connections are added to a pool** that handle all sockets messages and **retrieved from the pool** on demand or  created if no connection is available/has been released. 

There is also an hard limit to the number of running connections: if the number of running connections (not released to the pool or closed) is greater than the maximum then the client requesting a new connection will wait until one is released. Which triggers some issue with tthe application that don't read the body or release the socket (#274) .

## New design

The new design is removing the classic pool pattern by **implementing a Flow-based pattern** where instead of requesting a connection you're requesting a process implementing the needed resource (could be an TCP, Proxy, SSL connection or a Stream available (keepalive, pipelining, ...) . The resource will live in its own process. Requesting a resource is implying to ask for the main process dispatcher where is an available resource. Then send a message to it so it can be used by the  requester. This new design will **prevent any latency** in maintaining sockets messages + requests for a resource. Also it will **ease the detection of failures** by isolating a socket.

The new design is also add a new workflow improving the detection of idle requests, forcefully closing them if the requester didn't notified the resource in time.

This issue will fix #274 #224 #257 #191

**Comment by rlipscombe** [comment]
Sounds interesting. Do you have any pointers to documentation (blogs/papers) with more details about this "flow-based pattern", particularly as implemented in Erlang?

**Comment by benoitc** [comment]
@rlipscombe you have similar design implemented in [varpool](https://github.com/okeuday/varpool) or [sbroker](https://github.com/fishcakez/sbroker) .

The wikipedia is also a good introduction for it:
https://en.wikipedia.org/wiki/Flow-based_programming

**Comment by rlipscombe** [comment]
Some stuff to read :) Thanks.

**Comment by edgurgel** [comment]
:+1:

**Comment by lazedo** [comment]
can you check https://github.com/benoitc/hackney/issues/275 regarding `min_available` ?

**Comment by saa** [comment]
Any news?

**Comment by benoitc** [comment]
@saa it will land next week.

**Comment by saa** [comment]
@benoitc very cool
