### ISSUE TITLE
Utf8 not soruced properly

### ISSUE THREAD

**Issue by nOmi7** [benoitc/hackney#280]
I want to read unicode chars but hackeny does not read it properly

{ok, StatusCode, RespHeaders, ClientRef}=hackney:request(get,"http://www.gazeta.ru",[],<<>>,[]).

Title i get is 

[<<"Ãëàâíûå íîâîñòè äíÿ - Ãàçåòà.Ru">>]

where as it should be 
<meta property="og:title" content="Главные новости дня - Газета.Ru" />

Thanks

**Comment by benoitc** [comment]
which headers do you get? Trying to see if i could detect it and then possibly return an utf8 binary

**Comment by benoitc** [comment]
@nOmi7 tried the following:

```erlang
3> {ok, StatusCode, RespHeaders, ClientRef}=hackney:request(get,"http://www.gazeta.ru",[],<<>>,[]).
{ok,200,
    [{<<"Server">>,<<"nginx">>},
     {<<"Date">>,<<"Sun, 28 Feb 2016 15:56:14 GMT">>},
     {<<"Content-Type">>,<<"text/html; charset=windows-1251">>},
     {<<"Transfer-Encoding">>,<<"chunked">>},
     {<<"Connection">>,<<"keep-alive">>},
     {<<"Cache-Control">>,<<"max-age=60">>},
     {<<"Expires">>,<<"Sun, 28 Feb 2016 15:57:14 GMT">>},
     {<<"Access-Control-Allow-Origin">>,<<"*">>}],
    #Ref<0.0.3.1846>}
4> hackney:body(ClientRef).
{ok,<<" <!DOCTYPE html>\n<html>\n<head> \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                          \n    "...>>}
5>
```

It seems the charset is windows-1251, is the remote server expected to return an UTF-8 response?

**Comment by benoitc** [comment]
Also make sure your application is able to handle UTF8:
http://erlang.org/doc/apps/stdlib/unicode_usage.html

By itself hackney doesn't do any transformation there.

**Comment by nOmi7** [comment]
This can be closed it was not the header but the Body , i had to convert it manually 
I am good thanks .

**Comment by benoitc** [comment]
thanks for the feedback!
