### ISSUE TITLE
"unknown ca" error on GET request -- ssl_options / cacert options discarded 

### ISSUE THREAD

**Issue by brado** [benoitc/hackney#281]
I originally posted this in the httpoison project issues, as that is the library I am using directly to make my POST request. However, httpoison uses hackney, and I believe this problem is coming from hackney. Here's is the issue posted to httpoison, for reference: 

https://github.com/edgurgel/httpoison/issues/119

Anyway, I am getting the following error when I attempt a GET operation:
```
22:08:59.118 [error] SSL: :certify: ssl_handshake.erl:1490:Fatal error: unknown ca

** (FunctionClauseError) no function clause matching in Purest.MyAPI.handle_response/1
    (purest) lib/purest/my_api.ex:18: Purest.MyAPI.handle_response({:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'unknown ca'}}})
```
I have no problems hitting the URL in question within any browser, or curl. When I execute the following: 
```
openssl s_client -showcerts -connect <host:port -- redacted>
```
I get the following output:
```
CONNECTED(00000003)
1608:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59/src/ssl/s23_lib.c:185:
```
Hmmmm...I'm not learned enough about the differences between what OpenSSL does under the hood vs. popular browsers and curl (in fact I would have expected some of them to be using OpenSSL) to be able to draw any solid conclusions about that. 

What I can tell you is that the CA which would validate the certificate securing this server is one of ours, which raises a question about the key-store hackney leverages (mentioned below).

I am using the following dependencies:

httpoison: 0.8.1
hackney: 1.4.9

I am also using:

Erlang/OTP 18
Elixir 1.2

Also, when I turn off hackney's certificate validation with the insecure option, the request works fine. This raises the following questions: 
 
1. Most importantly, how can I fix this error? I can't go into production with the insecure option turned on, I need certification validation of course.

2. I'm running on OS X -- what does hackney reference as its key-store? Does it use the OS X Keychain, or does it use its own (or Elixir's -- I have no idea if Elixir uses its own key-store or not). 

Thanks in advance.

Brad

**Comment by brado** [comment]
One more note, executing the following: 
```
iex(3)> :hackney.get("https://<host>:<port>")
```
gives me this: 
```
10:09:27.575 [error] SSL: :certify: ssl_handshake.erl:1490:Fatal error: unknown ca

{:error, {:tls_alert, 'unknown ca'}}
```
So this is definitely happening within hackney...help is greatly appreciated!

**Comment by brado** [comment]
More data -- as mentioned, I'm experiencing this problem on OS X (El Capitan). I have tested this (not using hackney, but showing certs with OpenSSL) on Windows, and it is able to properly grab the certs from the host in question. 

As stated, Safari is working just fine, as is Paw (my OS X HTTP client app) are working just fine, as they leverage OS X's Keychain, into which our root CA which validates the host cert in question is installed. So I'm guessing that the problem is that OpenSSL and hackney are not using the OS X Keychain. If this resonates and is accurate, if anyone could point me in the right direction as to what has to be done on OS X (and for that matter any other platform) to get it to properly see a root CA, that would be great. Thanks.

**Comment by brado** [comment]
I have spent the day with this, and I believe I've solved the problem, and it dealt with hackney not being able to see root certs. I have been able to successfully test this from httpoison (which as you'll recall is where this issue began, and I drilled down into hackney. Unfortunately, I'm stuck on a newbie syntax issue, and while I can get the call to work using httpoison, I don't seem to be able to get the options formatted properly for a direct call to hackney. Here's the httpoison call which works: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
HTTPoison.post(@body_login, @http_headers, hackney: opts)
```
I tried adjusting the call for hackney, to this: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
:hackney.get("https://<host>:<port>", opts)
```
Unfortunately, that didn't work. it fails with the same "unknown ca" error. If anyone can help me reformat the opts so that this direct hackney call works, then I'm confident that this issue can be closed. Thanks in advance for your help.

**Comment by brado** [comment]
I have further troubleshooted this issue, and have discovered that I had made the foolish assumption that options on GET operations were being handled similarly to options on POST operations. They are not, and there is a problem here. Keep in mind, I'm coming from a higher layer up, using httpoison, which is using hackney (but the problem appears to be in hackney). When using :dbg, looking at the output, when doing this: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
HTTPoison.post(@body_login, @http_headers, hackney: opts)
```
this succeeds, because hackney passes the options properly to its underlying call to **hackney:maybe_proxy**. But if this same thing is attempted with a POST operation, as in: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
HTTPoison.get(@url, hackney: opts)
```
this fails, same as the direct call to hackney, because hackney completely drops the options entirely to its underlying call to **hackney:maybe_proxy**. I do not know if this is ultimately a problem with hackney, or something httpoison is not sending in its call to hackney, but it appears there is an issue here.

**Comment by benoitc** [comment]
i don't see in the code where the options could be skipp d though... what let you think that?

**Comment by brado** [comment]
Well I'll admit I'm not the expert yet at deciphering the hieroglyphs, but here is what I see in the debug output for a hackney GET:
```
iex(7)> opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
[ssl_options: [cacertfile: "/Users/bohearne/Desktop/MyCertificates.pem"]]
 
iex(8)> :hackney.get("https://myfictionalwebsite.com:3030", opts)

 (<0.153.0>) call hackney:get(<<"https://myfictionalwebsite.com:3030">>,[{ssl_options,[{cacertfile,<<"/Users/bohearne/Desktop/MyCertificates.pem">>}]}])
 
 (<0.153.0>) call hackney:request(get,<<"https://myfictionalwebsite.com:3030">>,[{ssl_options,[{cacertfile,<<"/Users/bohearne/Desktop/MyCertificates.pem">>}]}])

 (<0.153.0>) call hackney:request(get,<<"https://myfictionalwebsite.com:3030">>,[{ssl_options,[{cacertfile,<<"/Users/bohearne/Desktop/MyCertificates.pem">>}]}],<<>>,[])

 (<0.153.0>) call hackney:request(get,{hackney_url,hackney_ssl_transport,https,
              <<"myfictionalwebsite.com:3030">>,<<"/">>,<<"/">>,              <<>>,<<>>,"myfictionalwebsite.com",3030,<<>>,<<>>},[{ssl_options,[{cacertfile,<<"/Users/bohearne/Desktop/MyCertificates.pem">>}]}],<<>>,[])

 (<0.153.0>) call hackney:maybe_proxy(hackney_ssl_transport,"myfictionalwebsite.com",3030,[])

 11:16:01.300 [error] SSL: :certify: ssl_handshake.erl:1490:Fatal error: unknown ca
```
In the output above, the **maybe_proxy** call has no options associated. But if you issue a POST to the same host:port with the exact same options, here's what I see in the **maybe_proxy** line of the debug output: 
```
 (<0.153.0>) call hackney:maybe_proxy(hackney_ssl_transport,"myfictionalwebsite.com.com",3030,[{ssl_options,[{cacertfile,<<"/Users/bohearne/Desktop/MyCertificates.pem">>}]}])
```
The difference is pretty clear -- the ssl_options and cacertfile are being passed to the call in the POST (and the POST succeeds), but the options are not being passed to the call in the GET (and the GET fails). I may not be inferring things correctly, but it is the only thing I'm seeing that jumps out at me for the reasons that the POST is succeeding but the GET is failing. Ideas?

**Comment by benoitc** [comment]
hrm i think  that's because you're not passing the options to the right place. If you use `hackney:get/2` the second argument is an header. Try instead `hackney:get(URL, Headers, <<>>, Options)` . It should work. let me know, I will testi myself in the morning.

**Comment by brado** [comment]
That was it....strange it didn't manifest itself sooner in the food chain. That problem was passed all the way through httpoison to hackney and even looking at the debug output it wasn't immediately clear what the problem was. Thanks for much for your help.

**Comment by benoitc** [comment]
@brado i reckon it could be improved. also logging that the connnection is insecure which would have give you a hint. I will work on that soon. Thanks for the feedback anyway!

**Comment by brado** [comment]
I really appreciate you taking the time to look into this -- I appreciate the work you've done on this library, and though I'm new to phoenix / Elixir / Erlang, I am now using it heavily, and plan to be using hackney by extension heavily for the foreseeable future. Any help I can lend I'd be glad to. I hope this weird use case issue will help improve things going forward. Cheers!
