### ISSUE TITLE
 Request with Chunked Transfer Coding

### ISSUE THREAD

**Issue by ln5** [benoitc/hackney#285]
Am I supposed to be able to make Hackney send a request using "Chunked Transfer Coding" as described in RFC2616 section 3.6.1 by simply setting the "Transfer-Encoding" header to "chunked"? What I observe doesn't look like what I'd expect. IIUC chunking should happen over the body rather than the full request.

Client end:
> 1> {ok, Conn} = hackney:connect(hackney_url:parse_url("http://localhost:4747/"), []), 
> hackney:send_request(Conn, {get, <<"/">>, [{"Transfer-Encoding", "chunked"}], <<>>}).
> {error,timeout}
> 2>

Server end:
> $ nc -lp 4747
> 5f
> GET / HTTP/1.1
> Transfer-Encoding: chunked
> User-Agent: hackney/1.4.9
> Host: localhost:4747
> 
> 
> 0
> 

This is a simplified example. My real case for using chunking is when POST:ing more than 1MB, in which case I bump into a limitation at the server.

**Comment by benoitc** [comment]
if you want to stream the request don't pass a body but a stram atom or a
function. Looks at the readme.

I will have a closer look on the timeout issue when i'm back at my desk.
can you eventually send me a trace by enabling hackney_trace?

**Comment by ln5** [comment]
OK, I'm using hackney wrong. Will look into 'stream'.

Don't mind the timeout -- there were no real HTTP server at the other end.

Thanks.

**Comment by benoitc** [comment]
closing the issue since I guess it has been answered :)
