### ISSUE TITLE
rebar.lock and rebar.config.script is causing trouble in compilation as part of the deps

### ISSUE THREAD

**Issue by linearregression** [benoitc/hackney#301]
I have to remove rebar.lock and rebar.config.script to make it compile as deps
===> Evaluating config script "/Users/etsang/splunk/nevro/_build/default/lib/hackney/rebar.config.script"
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: {badmatch,
                            {error,
                              {44,file,
                              {error,
                                {badmatch,
                                ["3","0","0+build","272","ref7d29b74"]},
                                [{erl_eval,expr,3,[]}]}}}}
===> Stack trace to the error location: [{rebar_config,consult_file_,
                                                1,
                                                [{file,
                                                  "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_config.erl"},
                                                  {line,106}]},
                                                {rebar_config,consult_file,1,
                                                [{file,
                                                  "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_config.erl"},
                                                  {line,90}]},
                                                {rebar_app_utils,dep_to_app,
                                                7,
                                                [{file,
                                                  "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,164}]},
                                                {rebar_app_utils,
                                                '-parse_deps/6-lc$^0/1-0-',6,
                                                [{file,
                                                  "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,98}]},
                                                {rebar_app_utils,
                                                '-parse_deps/6-lc$^0/1-0-',6,
                                                [{file,
                                                  "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,98}]},
                                                {rebar_prv_install_deps,
                                                handle_dep,6,
                                                [{file,
                                                  "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                  {line,280}]},
                                                {rebar_prv_install_deps,
                                                update_unseen_dep,9,
                                                [{file,
                                                  "/home/tr

**Comment by benoitc** [comment]
which version of hackney are you using? I don't reproduce it there.

**Comment by linearregression** [comment]
1.5.0

**Comment by benoitc** [comment]
yeah you should use the 1.5.2 or 1.5.3 that should solve your issue. the
format of the rebar3 version string changed when it became stable.

**Comment by benoitc** [comment]
fixed in latest master
