### ISSUE TITLE
calls undefined function ssl:seed/1

### ISSUE THREAD

**Issue by alexshavelev** [benoitc/hackney#309]
==> hackney (xref)
src/hackney_pool.erl:207: Warning init/1 calls undefined function ssl:seed/1

**Comment by benoitc** [comment]
which vrsion of erlang?

**Comment by alexshavelev** [comment]
i've tried with 18.2
r15b03-1
r16b03

**Comment by alexshavelev** [comment]
as i've mentioned this function is from old erlang packages, now 'old_ssl' (http://erlang.org/documentation/doc-5.8.5/lib/ssl-4.1.6/doc/html/old_ssl.html) and doesn't apperars in newest http://erlang.org/documentation/doc-5.4.13/lib/ssl-3.0.11/doc/html/ssl.html()

**Comment by benoitc** [comment]
fixed in latest master
