### ISSUE TITLE
Get HTTPS page through proxy 

### ISSUE THREAD

**Issue by ColdFreak** [benoitc/hackney#310]
I have problem to get `https` resource through a proxy

When I `get` a  `http` resource, it works fine
```
iex(2)> :hackney.request(:get, "http://httparrot.herokuapp.com/get", [], "", [proxy: "http://proxy01.local:8080"])
{:ok, 200,[.....], #Reference<0.0.12.494>}
```

But When I `get` a `https` resource through proxy, it returns `false`, **the proxy is using `http`**

```
iex(1)> :hackney.request(:get, "https://api.github.com", [], "", [proxy: "http://proxy01.local:8080"])
false
```

The typespec of `request` is below, `false` is not in it, am I doing something wrong?
```
-spec request(term(), url() | binary() | list(), list(), term(), list())
    -> {ok, integer(), list(), client_ref()}
    | {ok, integer(), list()}
    | {ok, client_ref()}
    | {error, term()}.
```

**Comment by danabr** [comment]
See PR #320 for a fix for the return value.

Your proxy sent something unexpected back to hackney. Either check your proxy's logs, or trace [hackney_http_connect:check_status/1](https://github.com/benoitc/hackney/blob/master/src/hackney_http_connect.erl#L182).

**Comment by ColdFreak** [comment]
Thank you for the PR link, I should check the proxy's log first.

**Comment by benoitc** [comment]
@ColdFreak was it solved?
