### ISSUE TITLE
Queued request to a different destination hangs forever if no previous request to the same destination completes

### ISSUE THREAD

**Issue by ZeWaren** [benoitc/hackney#312]
## Introduction

When all the connections of a pool are in use, new requests are put in a queue and wait for a request to complete.
Problem: queued requests only get a connection when a request for the same destination completes. If the queued request is the first to a specific host, it will stay there forever.
## How to reproduce:
1. Start a pool of size N.
2. Start N requests to a specific destination (host+port) that takes time to answer: example.com.
3. Start another request to another destination: example.net.
## What happens:
1. Since the pool is currently fully in use, it will put the request to `example.net` in a queue and wait for a connection to that destination to be available.
2. The requests to `example.com` will complete, and the pool will try to find queued requests to the same destination. None will be found. (see function [`deliver_socket`](https://github.com/benoitc/hackney/blob/5215daf30de9ee9ed456f8c057b8f6f74191edec/src/hackney_pool.erl#L476) in module `hackney_pool`)
3. The request to example.net will stay in the queue forever.
## What should happens:

When the requests to `example.com` completes and the connections free space in the pool, queued request to other destinations should start.

**Comment by ZeWaren** [comment]
Here's a sample app that reproduces the bug: https://github.com/ZeWaren/hackney_pool_debug

**Comment by benoitc** [comment]
@ZeWaren thanks I will have a look tonight and will try to reproduce it :)

**Comment by benoitc** [comment]
actually this is how the pool it supposed to work. The pool is a limiting pool. The current solution is to use your own pooling strategy or not using a pool. This will be fixed in next release.
