### ISSUE TITLE
Encode "(" and ")" in path segment

### ISSUE THREAD

**Issue by asakura** [benoitc/hackney#314]
Should "(" and ")" be "percent" encoded in path segment (see example below)? 

```elixir
iex(4)> :hackney.request(:get, "https://api.linkedin.com/v1/people/~:(id,num-connections,picture-url)?format=json", [], "", [])
.....skipped....
[hackney trace 40 <0.282.0> 2016:05:05 13:48:28 4992] perform request 
   Content: [{module,hackney_request},
             {line,97},
             {header_data,<<"GET /v1/people/~:%28id,num-connections,picture-url%29?format=json HTTP/1.1\r\nUser-Agent: hackney/1.6.0\r\nHost: api.linkedin.com\r\n\r\n">>},
             {perform_all,true},
             {expect,false}]
....skipped....
```

If yes, how can I workaround this and send <<"GET /v1/people/~:(id,num-connections,picture-url)?format=json .... (ie skip any URL normalization) instead?

Thanks in advance.

**Comment by benoitc** [comment]
If you want a custom normalization you can pass the option `{path_encode_fun, Fun}` 

To completely ignore: `fun(Path) -> Path end.` The current function is here:
https://github.com/benoitc/hackney/blob/master/src/hackney_url.erl#L368

**Comment by asakura** [comment]
That is totally working solution, thanks!

**Comment by anthonylebrun** [comment]
Fantastic. I was using https://github.com/scrogson/oauth2/ which is powered by hackney and this was the issue I was facing :)

Just to others who had the same issue as I:

```
OAuth2.Client.get!(client, "/v1/people/~:(id,num-connections,picture-url)?format=json", [], [path_encode_fun: &(&1)])
```
