### ISSUE TITLE
rebar3 check for deps should include mix

### ISSUE THREAD

**Issue by ericmj** [benoitc/hackney#316]
This check should include mix https://github.com/benoitc/hackney/blob/master/rebar.config.script#L1. A possible solution would be to check for rebar2 instead.

**Comment by benoitc** [comment]
@ericmj how to check mix?

**Comment by ericmj** [comment]
Hum, I'm not sure what the best way is. One solution would be to instead try to check for rebar2 with `function_exported`, then you would have this check: `if rebar2 { rebar2 deps } else { rebar3 or mix deps }`.

**Comment by benoitc** [comment]
@ericmj just to make sure I understand the issue. But why mix is using rebar.config if `mix.exs` present in the source?

**Comment by ericmj** [comment]
If you use it from hex it should just work since we ignore the deps in rebar.config(.script) then. But when used from git we have different rules. If hackney is a dependency of another rebar3 dependency we will also treat hackney as a rebar3 project (because some people leave mix.exs files for package publishing in their project even though it doesn't compile with mix).

I don't recall exactly what raised this issue.

**Comment by benoitc** [comment]
I didn't reproduced it so closing it now. Feel free to reopen it if needed.

**Comment by ericmj** [comment]
I'm guessing you can't reproduce because you use hackney as a hex dependency. You need to add it as a git dependency to reproduce.
