### ISSUE TITLE
improve multipart documentation

### ISSUE THREAD

**Issue by alexshavelev** [benoitc/hackney#319]
Hi!
i need make this request - https://core.telegram.org/bots/api#sendphoto and attach file via multipart, but can't find the way how can do it in docs

can you help me and i will make pull request for docs?
Thanks

**Comment by alexshavelev** [comment]
@silviucpp maybe you can help with it

**Comment by benoitc** [comment]
@alexshavelev maybe this can help: https://github.com/benoitc/hackney/blob/master/doc/hackney_multipart.md#encode_form1 ?

**Comment by alexshavelev** [comment]
@benoitc maybe. but as a result i will get {Bin, Len}. what have to do next with id? which func call?

**Comment by benoitc** [comment]
can you paste a snippet of your code ? not sure iunderstand what's you're doing right now

**Comment by alexshavelev** [comment]
@benoitc [{<<"descr">>, <<"sunny day">>}, {<<"file">>, <<"path/to/file"}]
i need to send file and 1-2 additional fields with descriptions

**Comment by benoitc** [comment]
duplicate of #292
