### ISSUE TITLE
SSL session being reused when reuse_sessions: false

### ISSUE THREAD

**Issue by filipecabaco** [benoitc/hackney#322]
It seems that sessions are being reused even when the ssl options flag reuse_sessions: false is set.

Thanks to this we are able to successfully make a HTTPS request with a invalid cert and key if previously a valid cert and key was used to make a request.

See https://github.com/filipecabaco/ssl_test to see a very small use case.

Am I missing something? I tried to debug it but the flag seemed to be passed down to erlang's ssl module. 

Thanks for the help.

PS: The example was written using Elixir and HTTPoison. Meanwhile HTTPoison was already checked (https://github.com/edgurgel/httpoison/issues/139)

**Comment by benoitc** [comment]
@filipecabaco whatr let you think ssl sessions are reused?

**Comment by filipecabaco** [comment]
In the small demo made in Elixir, the test makes a call with a valid certificate and then another one with a incorrect certificate, I would expect it to fail on this second request but it doesn't so it seems that it's retaining some kind of state from the first request:
https://github.com/filipecabaco/ssl_test/blob/master/test/certs_test.exs

The flag of `reuse_sessions` is set to false here https://github.com/filipecabaco/ssl_test/blob/master/lib/cert.ex#L12

Have I missed the real intent of the flag `reuse_sessions`?

**Comment by benoitc** [comment]
It is probably just reusing a socket in the pool imo.  I need to fix that behavior. Can you try with setting the pool to none ?

**Comment by filipecabaco** [comment]
Made some changes to my code since this was some time ago and it was lacking stability even with such simple tests...

https://github.com/filipecabaco/ssl_test/blob/master/lib/cert.ex#L13

Passed the option to set `:pool` to `nil` which I would expect to avoid the usage of pools but the tests still fail meaning that I was able to successfully make the call with the wrong key

Should I set it do a different value?

**Comment by benoitc** [comment]
`nil` is not expected. You need to pass `false` to the pool or set the environment setting `use_default_poo`l to `false` . Then it shouldn't use a pool.

**Comment by filipecabaco** [comment]
Setting the pool to `false` in the hakney options was enough, now it throws `{:error, %HTTPoison.Error{id: nil, reason: {:keyfile, {:badmatch, []}}}}` which was the desired result.

Thank you so much for the help with the issue.
