### ISSUE TITLE
Typo in exometer instructions & `mod_metrics`

### ISSUE THREAD

**Issue by ctreatma** [benoitc/hackney#323]
The instructions for setting up metrics with exometer in the README specify that exometer metrics should be enabled by specifying `{mod_metrics, exometers}`.  However, `mod_metrics` expects the first term in the tuple to match `folsom`, `exometer` (no 's'), or `dummy`.

If `{mod_metrics, exometer}` is configured, hackney attempts to initialize a module called `metrics_exometers`, but the module defined by the metrics library is called `metrics_exometer`.

**Comment by benoitc** [comment]
appear to be fixed in last master
