### ISSUE TITLE
Cannot install with OTP 18

### ISSUE THREAD

**Issue by dkarter** [benoitc/hackney#327]
```
==> hackney (compile)
ERROR: OTP release 18 does not match required regex R15|R16|17
ERROR: compile failed while processing /Users/dkarter/Dropbox/Developer/googlepos/deps/hackney: rebar_abort
** (Mix) Could not compile dependency :hackney, "/Users/xxx/.mix/rebar compile skip_deps=true deps_dir="/Users/xxx/xyz/zyx/googlepos/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"
```

Getting this when trying to install hackney from another dependency in my project. I'm quite new to Elixir so I'm not sure what to do short of downgrading my system erlang version.

**Comment by benoitc** [comment]
this dep is using an old version of hackney. Maybe you can force it in mix by depending directly on hackney?

**Comment by dkarter** [comment]
Thanks for your advice! :) I ended up using another web scraping package that uses ibrowse.
