### ISSUE TITLE
Options used to limit TLS versions and ciphers

### ISSUE THREAD

**Issue by heri16** [benoitc/hackney#329]
Hi there, could we have documentation on how to limit the TLS version and ciphers used by hackney? Specifically, we would like to pass in versions, ciphersuites, and secure_renegotiate from here: http://erlang.org/doc/man/ssl.html

**Comment by benoitc** [comment]
ssl_options accecpt all ssl options from the erlang module.

**Comment by benoitc** [comment]
now you can pass any options using `{connect_options, TransportOptions}` or `{ssl_options, SslOptions}` they will all pass.
