### ISSUE TITLE
Security: better defaults for ssl_opts

### ISSUE THREAD

**Issue by heri16** [benoitc/hackney#330]
Hackney currently fails security tests on SSLlabs. https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by benoitc** [comment]
it is failing 1 test apparently i will check what is this issue. thanks for
the test.

**Comment by benoitc** [comment]
can you please post the test you did? to make sure i can reproduce it ?
also which erlang version?

**Comment by heri16** [comment]
Just do a https request to that page with hackney and it should return HTML results which you could write to a file and view in any browser.

**Comment by heri16** [comment]
Just send a https get request to https://www.howsmyssl.com and the results would be in html

**Comment by heri16** [comment]
Alternatively, use the JSON api at  https://www.howsmyssl.com/s/api.html . It provides a rating.

**Comment by benoitc** [comment]
fixed in ltest master
