### ISSUE TITLE
SSL Handshake failure

### ISSUE THREAD

**Issue by Frogglet** [benoitc/hackney#339]
Any reason why hackney wouldn't be able to complete the handshake with the server at https://rev-int.api.us.fleetmatics.com? When I try to connect I get `{:error, :closed}` with no other info. I've run the server through the ssl labs test and it passes all handshake tests. Also, I can connect to it via node and curl just fine.

I'm not a networking guy, but in wireshark, it appears that right after hackney sends a ClientHello packet, the server responds with a packet that specifies a connection reset, and thats the last thing sent by either party.

Given that I can't find any other commonly-used http client to run into any problems with the server it seems pretty likely theres a bug here somewhere.

**Comment by benoitc** [comment]
which version of erlang? also can you shareme the snippet of the request
you're doing so o can try to reproduce?

**Comment by Frogglet** [comment]
I'm using Erlang 19 and hackney 1.6.0, and the simplest code to reproduce is just going to be 

    hackney:request(get, <<"https://rev-int.api.us.fleetmatics.com">>, [], <<>>, []).

HTTP data should be irrelevant since the error is occurring before the SSL connection is established. From that command I would ordinarily expect a 4xx http error response. 

FWIW I've just tried this with inets:

    httpc:request(get, {"https://rev-int.api.us.fleetmatics.com", []}, [], []).

and I received this error:

    {error,{failed_connect,[{to_address,{"rev-int.api.us.fleetmatics.com",
                                     443}},
                        {inet,[inet],closed}]}}

So whatever this is appears to be an Erlang-wide thing, and not specific to hackney. 

Also, from looking at response headers I've received from this server, it appears to be running IIS 8.5. Any ideas?

**Comment by Frogglet** [comment]
Since this doesn't appear to be hackney specific, I'll close this and try to raise this issue elsewhere. Do let me know if I'm just missing something obvious.

Thanks,

**Comment by benoitc** [comment]
@Frogglet it can probably be solved by using alternative SSL transport like one suggested in #332 . I will open a repo for it and let you now :)

**Comment by Frogglet** [comment]
Okay great, thanks!

**Comment by deadtrickster** [comment]
Hello Gentlemen! 

Erlang's SSL is strange but not always bad :-)

Given "C" rating from SSLLabs for the domain in question it's not a big surprise it doesn't work by default: https://www.ssllabs.com/ssltest/analyze.html?d=rev-int.api.us.fleetmatics.com

```erlang
ssl:connect("rev-int.api.us.fleetmatics.com", 443, [{versions, ['tlsv1.2']}]).   
{ok,{sslsocket,{gen_tcp,#Port<0.1439>,tls_connection,
                        undefined},
               <0.111.0>}}
```

My ball park guess is that server always tries to negotiate using sslv3 which isn't enabled by default.

```erlang
1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}
2> ssl:connect("rev-int.api.us.fleetmatics.com", 443, [{versions, ['sslv3']}]).
{ok,{sslsocket,{gen_tcp,#Port<0.725>,tls_connection,
                        undefined},
               <0.74.0>}}
3> ssl:versions().
[{ssl_app,"8.0"},
 {supported,['tlsv1.2','tlsv1.1',tlsv1]},
 {available,['tlsv1.2','tlsv1.1',tlsv1,sslv3]}]
```

Cheers!

**Comment by benoitc** [comment]
@deadtrickster true. It should work with the latest master though:

```
1> application:ensure_all_started(hackney).
{ok,[idna,mimerl,certifi,ssl_verify_fun,metrics,hackney]}
2> hackney:get("https://rev-int.api.us.fleetmatics.com").
{ok,401,
    [{<<"Cache-Control">>,<<"private">>},
     {<<"Transfer-Encoding">>,<<"chunked">>},
     {<<"Content-Type">>,<<"text/html; charset=utf-8">>},
     {<<"ETag">>,<<"FleetMatics">>},
     {<<"Server">>,<<"Microsoft-IIS/8.5">>},
     {<<"Set-Cookie">>,
      <<"ASP.NET_SessionId=5tcw4qd4lsggtlbbhnihzub4; path=/; HttpOnly">>},
     {<<"X-AspNetMvc-Version">>,<<"5.2">>},
     {<<"WWW-Authenticate">>,<<"Basic realm=\"Secure Area\"">>},
     {<<"Date">>,<<"Mon, 12 Sep 2016 11:22:39 GMT">>}],
    #Ref<0.0.2.2172>}
```

using the latest master that contains:
https://github.com/benoitc/hackney/commit/873ea3da8cac0238a2eb7f89429acd5456a3c3f3

**Comment by deadtrickster** [comment]
Yeah you explicitly list versions, why no tlsv1.2?

**Comment by benoitc** [comment]
because it's consired insecure.

**Comment by benoitc** [comment]
actually maybe not. i need  to verify again.

**Comment by deadtrickster** [comment]
Ssl v3 deprecated last year. TLS v1 isn't PCI compliant since May 2016. I believe TLS v1.2 still the most secure option.


Get Outlook for Android






On Mon, Sep 12, 2016 at 9:31 PM +0300, "Benoit Chesneau" <notifications@github.com> wrote:












actually maybe not. i need  to verify again.

**Comment by deadtrickster** [comment]
any news on tlsv1.2?

**Comment by benoitc** [comment]
sure looks at 533254f1bc615550aa6a88e30d2a1785e5e3a93d

**Comment by deadtrickster** [comment]
Awesome! It's being a while since the last hex release so I thought it's worth asking

**Comment by deadtrickster** [comment]
Not sure having sslv3 enabled by default is a good idea though.

**Comment by AlimovSV** [comment]
The same problem:
```
iex(1)>  :hackney.request :get, "https://vpic.nhtsa.dot.gov/api/vehicles/decodevinvalues/5UXWX7C5*BA?format=json&modelyear=2011"
{:error, :closed}
```
but
```
iex(1)> :ssl.connect('vpic.nhtsa.dot.gov', 443, [versions: [:"tlsv1.2"]]) 
{:ok,
 {:sslsocket, {:gen_tcp, #Port<0.7940>, :tls_connection, :undefined},
  #PID<0.290.0>}}
iex(2)> :hackney.request :get, "https://vpic.nhtsa.dot.gov/api/vehicles/decodevinvalues/5UXWX7C5*BA?format=json&modelyear=2011"
{:ok, 200,
 [{"Cache-Control", "no-cache"}, {"Pragma", "no-cache"},
  {"Content-Type", "application/json"}, {"Expires", "-1"},
  {"Server", "Microsoft-IIS/8.5"}, {"X-AspNet-Version", "4.0.30319"},
  {"X-Powered-By", "ASP.NET"}, {"Access-Control-Allow-Origin", "*"},
  {"Date", "Tue, 08 Nov 2016 13:48:10 GMT"}, {"Content-Length", "3041"}],
 #Reference<0.0.1.78>}
```
Rank B: https://www.ssllabs.com/ssltest/analyze.html?d=vpic.nhtsa.dot.gov
```
defp deps do
  ...
  {:hackney, "~> 1.6.3"},
  ...
end
```
