### ISSUE TITLE
Bump idna

### ISSUE THREAD

**Issue by MSch** [benoitc/hackney#348]
It looks like there's already a version of idna out that doesn't require NIFs, but the current release of hackney still requires an old NIF-based version. Would it be possible to bump the idna dependency and release a new version?

**Comment by benoitc** [comment]
The current version of hackney don't require any nif version but the 1.2.0:
https://github.com/benoitc/erlang-idna/tree/40c682fef283b7c3871c4b59aa0469304c6613ef

which version are you referring to?

**Comment by benoitc** [comment]
closing issue. hackney don't use a nif version of idna.
