### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by henry40408** [benoitc/hackney#350]
`src/hackney_pool.erl:213: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1`

`src/hackney_multipart.erl:271: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead`

Erlang version: **19.1**
Elixir version: **1.3.3**
`hackney` version: **1.6.1**

**Comment by benoitc** [comment]
It should be fixed in latest master. Let me know :)

**Comment by henry40408** [comment]
Would it be published as next release, such as `1.6.2`?

**Comment by benoitc** [comment]
hackney 1.6.2 has been released :)
