### ISSUE TITLE
Version 1.6.2 in hex.pm has version = 1.6.1 in mix.exs

### ISSUE THREAD

**Issue by rhruiz** [benoitc/hackney#354]
The version 1.6.2 of the tarball in hex.pm (https://repo.hex.pm/tarballs/hackney-1.6.2.tar) is published with `version: "1.6.1",` in its `mix.exs` file.

So when I have in my `mix.exs` file:

`{:hackney, ">= 1.6.2"},`

it will download the correct tarball:

```
mix deps.get
Running dependency resolution
* Getting hackney (Hex package)
  Checking package (https://repo.hex.pm/tarballs/hackney-1.6.2.tar)
```

but running my app fails with:

```
mix run
Unchecked dependencies for environment dev:
* hackney (Hex package)
  the dependency does not match the requirement ">= 1.6.2", got "1.6.1"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by benoitc** [comment]
@rhruiz fixed and uploaded to hex. Thanks!

**Comment by timmak** [comment]
Don't know if this is a hex issue but this is still a problem

**Comment by benoitc** [comment]
@timmak what is the issue? hex has 1.6.3.

**Comment by timmak** [comment]
1.6.2 tar file still as has 1.6.1 in the config. Couchbeam use 1.6.2 which is cause a dependency issue.

**Comment by benoitc** [comment]
@timmak well then couchbeam needs a patch.. Can you open a ticket for it? For sure 1.6.2 will stay 1.6.2 :)
