### ISSUE TITLE
Unable to use couchbeam with hex mix.exs, wrong version for 1.6.2

### ISSUE THREAD

**Issue by brainlid** [benoitc/hackney#360]
Installing couchbeam ~> 1.4 requires version 1.6.2 of hackney. The hackney mix.exs file for version 1.6.2 reports hackney version as 1.6.1. So compilation fails.

Please correct the 1.6.2 branch's mix.exs file to report the correct version of hackney.

Here's a link to the 1.6.2 branch of hackney. The mix.exs file reports version 1.6.1.

https://github.com/benoitc/hackney/blob/1.6.2/mix.exs#L7

**Comment by benoitc** [comment]
this has been fixed in 1.6.3 of hackney.  I will check if couchbeam need to be updated. Thanks for the report anyway :)
