### ISSUE TITLE
Pool running out of connections, but why?

### ISSUE THREAD

**Issue by nlfiedler** [benoitc/hackney#371]
I've written a client library for Google Cloud Storage in Erlang, and I'm using hackney for the HTTP calls. There are various types of calls (e.g. get, put, post, patch, delete), and in testing this all seems to work fine. However, with a long running application that is uploading many files to the cloud, I eventually run out of connections in the pool. I'm using the default pool and default settings. If I understand correctly, the `hackeny:request` functions should manage the connection automatically. Are there circumstances where that is not the case?

The stack trace below shows where it eventually gets stuck.

```
> erlang:process_info(pid(0,82,0), current_stacktrace).
{current_stacktrace,[{gen,do_call,4,
                          [{file,"gen.erl"},{line,169}]},
                     {gen_server,call,3,[{file,"gen_server.erl"},{line,208}]},
                     {hackney_pool,checkout,4,
                                   [{file,"/usr/home/nfiedler/akashita/_build/default/lib/hackney/src/hackney_pool.erl"},
                                    {line,66}]},
                     {hackney_connect,socket_from_pool,4,
                                      [{file,"/usr/home/nfiedler/akashita/_build/default/lib/hackney/src/hackney_connect.erl"},
                                       {line,187}]},
                     {hackney_connect,connect,5,
                                      [{file,"/usr/home/nfiedler/akashita/_build/default/lib/hackney/src/hackney_connect.erl"},
                                       {line,37}]},
                     {hackney,request,5,
                              [{file,"/usr/home/nfiedler/akashita/_build/default/lib/hackney/src/hackney.erl"},
                               {line,328}]},
                     {enenra_server,upload_file,4,
                                    [{file,"/usr/home/nfiedler/akashita/_build/default/lib/enenra/src/enenra_server.erl"},
                                     {line,279}]},
                     {enenra_server,request_with_retry,3,
                                    [{file,"/usr/home/nfiedler/akashita/_build/default/lib/enenra/src/enenra_server.erl"},
                                     {line,442}]}]}
```

The enenra library is on GitHub, and all of the hackney calls are in this file: https://github.com/nlfiedler/enenra/blob/master/src/enenra_server.erl

**Comment by benoitc** [comment]
@nlfiedler It can happen if you're not reading the body or you have a long response to receive. I will try to have a look at your code by tomorrow to check what's happening

**Comment by nlfiedler** [comment]
I was just wondering if I'm supposed to call `hackney:body` or `hackney:skip_body` every time, otherwise maybe the client is left hanging around. That wasn't obvious from the README and module reference. I'll give that a try. Thanks.

**Comment by benoitc** [comment]
Things will change soon makiing the api more explicit about it.

Anyway, apparently you got your answer :) Closing the issue then :)

**Comment by nlfiedler** [comment]
Yep, I made the fix and it ran all night without any problems. Thanks for your help.
