### ISSUE TITLE
No dependencies in Hex package

### ISSUE THREAD

**Issue by ericmj** [benoitc/hackney#372]
Seems like the last publish was broken: https://hex.pm/packages/hackney/1.6.4

**Comment by benoitc** [comment]
it seems that the version of rebar3 i'm using is broken somehow and unable to get the list of dependencies. I'm trying with the new one. Thanks for the notice!

**Comment by benoitc** [comment]
opened a ticket on the rebar3 project related to it: erlang/rebar3#1427

**Comment by benoitc** [comment]
fixed. Somehow rebar3_hex plugin needed to be updated.

**Comment by benoitc** [comment]
1.6.5 has been released
