### ISSUE TITLE
Enhancement: Provide for optional reconnection hooks

### ISSUE THREAD

**Issue by garryh** [benoitc/hackney#380]
In most cases, Hackney's reconnect feature is a good thing. But in certain security applications it is necessary to have more control over the reconnection process. For example, when using [Single Packet Authorization(SPA)](http://www.cipherdyne.org/fwknop/), a connection cannot be made without first sending an SPA packet to open up a temporary pinhole firewall. For the initial connection, we can send the SPA packet before doing a Hackney request (as we currently do with httpc), and all is well. But if the connection drops, Hackney will be unable to reconnect because the firewall will have reverted to drop all new connections. 

This could be addressed in several ways:

- Add an option { reconnect, boolean() } to allow for disabling reconnections.
- Add an option to pass a fun to be called before connecting, like { preconnect, fun() }. We could then pass a fun() to do the port knocking prior to connect/reconnect. Might as well add a { post_connect, fun() } as well. There could be other uses for these, like logging reconnects or collecting statistics on dropped connections.
- Add an option to pass a fun() to be called when connecting, that would actually do the connecting, returning a socket for Hackney to then use. This would allow the caller full control over the connection process.

I have not used Hackney to date, so I could be way off base here. Or perhaps there is already a way to accomplish what I need. If so, please correct any of my misunderstandings.

**Comment by benoitc** [comment]
duplicate of #161
