### ISSUE TITLE
malformed_handshake with Docker Engine API v1.13

### ISSUE THREAD

**Issue by barttenbrinke** [benoitc/hackney#381]
I'm using hackney to connect to Docker machine. This worked like a charm in version v1.12.5, until today. The latest version of docker is giving me the following issue:

```
$ curl https://188.166.86.204:2376/_ping \
  --cert ~/docker_workspaces/certs/cert.pem \
  --key ~/docker_workspaces/certs/key.pem \
  --cacert ~/docker_workspaces/certs/ca.pem

OK

iex>
options = [] \
  |> Keyword.merge([
  hackney: [
    ssl_options: [
      certfile: "~/docker_workspaces/certs/cert.pem",
      keyfile: "~/docker_workspaces/certs/key.pem",
      cacertfile: "~/docker_workspaces/certs/ca.pem"
    ]
  ]
])
HTTPoison.request(:get, "https://188.166.86.204:2376/_ping", "", [], options)

[error] SSL: :certify: tls_connection.erl:619:Fatal error: handshake failure - malformed_handshake
{:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'handshake failure'}}}
```

This is a new machine on digital ocean, installed through the docker-cli. I understand the issue might be hard to reproduce for you, so please let me know what extra information you need. Thanks!

**Comment by barttenbrinke** [comment]
This is probably related: https://github.com/docker/docker/issues/20085

**Comment by anronin** [comment]
I have exactly the same problem after upgrade to docker 1.13

**Comment by barttenbrinke** [comment]
No, that is not the issue as I am specifying the cacert. There has recently been a fix in Erlang which looks simular: http://erlang.org/pipermail/erlang-questions/2016-November/090785.html . I've compiled Erlang master using kerl and the issue seems solved there. Will need more investigation to be sure though.

**Comment by barttenbrinke** [comment]
This is fixed in Erlang 20. You can easily install this by buidling git,master using https://github.com/kerl/kerl . If you are lazy and use homebrew you can move it to /usr/local/Cellar/erlang/19.2/lib/erlang and everything will work again 👍
