### ISSUE TITLE
Race condition in pool resurrection?

### ISSUE THREAD

**Issue by palm86** [benoitc/hackney#385]
If a connection pool is supervised as follows:

`children = [
    :hackney_pool.child_spec(:my_pool, [timeout: 15000, max_connections: 1000])
]`

and if requests in which a pool (:my_pool) is specified create the pool if it doesn't exist, what guarantees that the supervisor brings the pool back up before some request brings it up (possibly with different max_connections and timeout)?

**Comment by benoitc** [comment]
Supervisors are gen_server, so you will get the old pool resurrected. There is a new connection system in progress, but I have been side tracked by a work. Will go back on the new release of hackney sometimes next week.

**Comment by benoitc** [comment]
answered
