### ISSUE TITLE
handshake error with hackney 1.6.2 and up. MacOSX sierra

### ISSUE THREAD

**Issue by gVolop** [benoitc/hackney#387]
use hackney 1.6.2 and up cause TLS handshake error 

i'm working on elixir project with HttpPoision, upgrade to last httpPoision version caused me the error. when i override hackney to 1.6.1 - all it okay. but all others hackney versions still raised the error when i try to call to https server.

i tried post request to https://www.googleapis.com/oauth2/v3/token to generate access token to google api.

error:
`SSL: certify: tls_connection.erl:688:Fatal error: handshake failure - malformed_handshake_data {error,{tls_alert,"handshake failure"}}`

________________________________________________________________________
MacOSX sierra 
```
~|⇒ elixir --version
Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Elixir 1.4.2
~|⇒ openssl version 
OpenSSL 0.9.8zh 14 Jan 2016
```

**Comment by benoitc** [comment]
@gVolop thanks for the report

When I try to post on that url though I get an error but not an ssl one (which is normal i don't send a correct header):

```erl
> hackney:head("https://www.googleapis.com/oauth2/v3/token").
{ok,404,
    [{<<"Cache-Control">>,
      <<"no-cache, no-store, max-age=0, must-revalidate">>},
     {<<"Pragma">>,<<"no-cache">>},
     {<<"Expires">>,<<"Mon, 01 Jan 1990 00:00:00 GMT">>},
     {<<"Date">>,<<"Sun, 26 Feb 2017 20:06:15 GMT">>},
     {<<"Vary">>,<<"X-Origin">>},
     {<<"Content-Type">>,<<"text/html; charset=UTF-8">>},
     {<<"X-Content-Type-Options">>,<<"nosniff">>},
     {<<"X-Frame-Options">>,<<"SAMEORIGIN">>},
     {<<"X-XSS-Protection">>,<<"1; mode=block">>},
     {<<"Server">>,<<"GSE">>},
     {<<"Alt-Svc">>,<<"quic=\":443\"; ma=2592000; v=\"35,34\"">>},
     {<<"Transfer-Encoding">>,<<"chunked">>},
     {<<"Accept-Ranges">>,<<"none">>},
     {<<"Vary">>,<<"Origin,Accept-Encoding">>}]}
```

Can you eventually try thtat directly in the erlang shell and let me know about your return? (I'm using Erlang 19.2.3)

**Comment by benoitc** [comment]
I updated the comment above with the POST request I wanted to paste.

**Comment by gVolop** [comment]
here is the result...

```
hackney|master ⇒ git checkout 1.6.6 
Note: checking out '1.6.6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c3f5fe7... bump to 1.6.6 and sync doc
hackney|c3f5fe7 ⇒ rebar3 compile
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Verifying dependencies...
===> Compiling hackney
hackney|c3f5fe7⚡ ⇒ rebar3 shell  
===> Verifying dependencies...
===> Compiling hackney
Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [smp:4:4] [async-threads:0] [kernel-poll:false]

Eshell V8.2  (abort with ^G)
1> hackney:start().
ok
2> hackney:post("https://www.googleapis.com/oauth2/v3/token", [], <<>>, [with_body]).

=ERROR REPORT==== 26-Feb-2017::22:43:55 ===
SSL: certify: tls_connection.erl:704:Fatal error: handshake failure - malformed_handshake_data {error,{tls_alert,"handshake failure"}}
3> 

```

**Comment by benoitc** [comment]
hrm so there is definitely something odd. I'm also on osx sierra:

```
[hackney] /usr/local/opt/openssl/bin/openssl version                                                                                                                              
OpenSSL 1.0.2j  26 Sep 2016
```

using latest tagged version of Erlang built with kerl:

```
[hackney] more ~/.kerlrc                                                                                                                                                          
KERL_DEFAULT_INSTALL_DIR=$HOME/local/otp
KERL_CONFIGURE_OPTIONS="--enable-shared-zlib --disable-dynamic-ssl-lib --with-ssl=/usr/local/opt/openssl --disable-hipe --enable-smp-support --enable-threads --enable-kernel-poll --with-wx --enable-darwin-64bit --without-odbc --enable-dirty-schedulers"
```

**Comment by gVolop** [comment]
what could it be???? 
@benoitc, any idea?
```
hackney|c3f5fe7⚡ ⇒ openssl version
OpenSSL 1.0.2k  26 Jan 2017

hackney|c3f5fe7⚡ ⇒ /usr/local/opt/openssl/bin/openssl version    
OpenSSL 1.0.2k  26 Jan 2017
```

erl - 19.2

**Comment by benoitc** [comment]
@gVolop i suspect an issue with your local build of Erlang. Maybe you can rebuild it using the options above and let me know?

**Comment by gVolop** [comment]
ok!
it's works!!!
i don't know what was with my old installation of erlang.. but after i completely remove it, and reinstall with brew all works properly.

many thanks @benoitc !

```
hackney|c3f5fe7⚡ ⇒ brew install erlang
==> Downloading https://homebrew.bintray.com/bottles/erlang-19.2.3.sierra.bottle.tar.gz
Already downloaded: /Users/gittelvolpo/Library/Caches/Homebrew/erlang-19.2.3.sierra.bottle.tar.gz
==> Pouring erlang-19.2.3.sierra.bottle.tar.gz
==> Caveats
Man pages can be found in:
  /usr/local/opt/erlang/lib/erlang/man

Access them with `erl -man`, or add this directory to MANPATH.
==> Summary
🍺  /usr/local/Cellar/erlang/19.2.3: 7,310 files, 280.9M
hackney|c3f5fe7⚡ ⇒ brew install elixir
==> Downloading https://homebrew.bintray.com/bottles/elixir-1.4.2.sierra.bottle.tar.gz
Already downloaded: /Users/gittelvolpo/Library/Caches/Homebrew/elixir-1.4.2.sierra.bottle.tar.gz
==> Pouring elixir-1.4.2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/elixir/1.4.2: 388 files, 5.5M
hackney|c3f5fe7⚡ ⇒ rebar3 compile
===> Verifying dependencies...
===> Compiling hackney
hackney|c3f5fe7⚡ ⇒ rebar3 shell  
===> Verifying dependencies...
===> Compiling hackney
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.2.2  (abort with ^G)
1> hackney:start().
ok
2> hackney:post("https://www.googleapis.com/oauth2/v3/token", [], <<>>, [with_body]).
{ok,400,
    [{<<"Vary">>,<<"X-Origin">>},
     {<<"Content-Type">>,<<"application/json; charset=UTF-8">>},
     {<<"Date">>,<<"Tue, 28 Feb 2017 18:16:30 GMT">>},
     {<<"Expires">>,<<"Tue, 28 Feb 2017 18:16:30 GMT">>},
     {<<"Cache-Control">>,<<"private, max-age=0">>},
     {<<"X-Content-Type-Options">>,<<"nosniff">>},
     {<<"X-Frame-Options">>,<<"SAMEORIGIN">>},
     {<<"X-XSS-Protection">>,<<"1; mode=block">>},
     {<<"Server">>,<<"GSE">>},
     {<<"Alt-Svc">>,<<"quic=\":443\"; ma=2592000; v=\"35,34\"">>},
     {<<"Accept-Ranges">>,<<"none">>},
     {<<"Vary">>,<<"Origin,Accept-Encoding">>},
     {<<"Transfer-Encoding">>,<<"chunked">>}],
    <<"{\n \"error\": \"internal_failure\",\n \"error_description\": \"Unsupported content with type: application/oc"...>>}
3> 
```

**Comment by BillSmargiassi** [comment]
Getting the same error with 19.2 for the Mac (Sierra 10.12.3) downloaded yesterday (2017-03-02) from Erlang Solutions as well:

```
exit with reason no match of right hand value {error,{hackney_error,{tls_alert,"handshake failure"}}}
```

The same code is working fine on Centos 7.3.

**Comment by benoitc** [comment]
@BillSmargiassi Erlang needs to be compiled with openssl (the one coming with brew or ports) and not with the crypto lib installed with default OSX. I guess the version of Erlang Solutions is based on it. 

I'm actually wondering though if there is a way to get more info about this handshake failure to report it upstream though. It would worth to have it to understand clearly the issue. Also which version of hackney are you using?

**Comment by gVolop** [comment]
@BillSmargiassi 
the installation of erlang solution didn't solve the issue for me. only after i completely uninstall Erlang, and i also manually remove all the files associated with. 
then i installed erlang with brew and the problem disappeared

**Comment by BillSmargiassi** [comment]
Once I deleted the Erlang Solutions version and installed from Homebrew, the problem disappeared. We're using hackney 1.6.2.

**Comment by brettwise** [comment]
I wasn't sure about where the files were that @gVolop & @BillSmargiassi mentioned deleting. 

On MacOS deleting `/usr/local/lib/erlang` and then running `brew install erlang` seems to do the trick. 

May need to `brew update` first.

**Comment by BillSmargiassi** [comment]
Yes @brettwise, that's what I meant.

**Comment by egeersoz** [comment]
Completely removing erlang and reinstalling the latest version didn't fix this for me.

**Comment by benoitc** [comment]
@egeersoz how did you install it?  also can you tell me how can I reproduce it? would help.

**Comment by egeersoz** [comment]
I use homebrew. First I did `homebrew uninstall --force` to uninstall Erlang (had to use the force command because I have Elixir, which depends on Erlang). Then I did `brew update` followed by `brew install erlang` which installed Erlang 19.3.

I'm using HTTPoison, which is an Elixir library:

```
HTTPoison.get("https://neutrinoapi.com")
```

This results in:

```
[error] SSL: :hello: ssl_alert.erl:88:Fatal error: handshake failure

{:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'handshake failure'}}}
```

There's a few tickets on HTTPoison on this but they are all closed saying this is a hackney bug.

**Comment by deadtrickster** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=neutrinoapi.com&hideResults=on

**Comment by deadtrickster** [comment]
Also: 

```
ssl:connect("neutrinoapi.com", 443, [{versions, ['tlsv1']}]).        
{ok,{sslsocket,{gen_tcp,#Port<0.1407>,tls_connection,
                        undefined},
               <0.98.0>}}
```

so nothing new :-)

**Comment by gVolop** [comment]
@egeersoz 
ru sure u completely uninstall erlang & elixir? for me, after homebrew uninstal still had erl command. so i had to remove it manually and after the cleanup - i had install rlang & elixir with brew

**Comment by egeersoz** [comment]
I didn't uninstall Elixir, since the problem is caused by Erlang. However, I uninstalled all versions of Erlang using `homebrew uninstall erlang --force`, and verified that it was gone by running `iex`, which gave an error saying it couldn't find `erl`.

**Comment by benissimo** [comment]
Reverting to 1.6.1 of Hackney solved the problem for me:

` {:hackney, "1.6.1", override: true }, `

That's the only change I made (didn't reinstall erlang, etc.)

**Comment by gVolop** [comment]
maybe it's solved the issue. but override to old versions it's not so recommended.

**Comment by benoitc** [comment]
Also the reason it is happening is because hackney is more stric now (which is a good thing). Which ssl version are you using?

**Comment by benissimo** [comment]
I had Apple's openssl:
OpenSSL 0.9.8zg 14 July 2015

Today I upgraded that, and removed and then reinstalled erlang:
```
brew update
brew install openssl
cd /usr/bin
sudo mv openssl openssl_apple
sudo ln -s /usr/local/Cellar/openssl/1.0.2k/bin/openssl /usr/bin/openssl
mkdir -p /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
openssl version -a
# OpenSSL 1.0.2k  26 Jan 2017
```

I then stopped overriding the version of Hackney, reinstalled dependencies in my Elixir app and:
```
iex(2)> :hackney.request(:get, "https://www.google.com/", [], "", [])                         
[error] SSL: :certify: tls_connection.erl:704:Fatal error: handshake failure - malformed_handshake_data
```

**Comment by aweiker** [comment]
I just had this issue as well. It turns out that I had a rogue erlang solutions install hanging around in `/usr/local/lib/erlang`.

**Comment by monkeygroover** [comment]
Ok, going to dump a series of observations here hopefully to clarify what seems to have happened.

1) Apple stopped shipping newer versions of openSSL after 0.9.8
2) homebrew used to work, but at some point they decided to stop symlinking the library into the global path as it can mess up other apps.

**Comment by lrascao** [comment]
```
restc:request(get, json, URL, [], [], [], [{ssl_options, [{versions, ['tlsv1']}]}]).
```
did the trick for me

**Comment by benoitc** [comment]
@lrascao it means that one of your server is not really secure. Hackney ensure a strict handhake. I guess you could have the same result by using the setting `insecure` also.

**Comment by lrascao** [comment]
that's interesting, i get the same error using the example on README.md
````
hackney:request(get, <<"https://friendpaste.com">>, [], <<>>, []).
````
... but only on OTP19, it works fine in OTP20
i built both OTP's in the same way, in the same machine (MacOS)

**Comment by benoitc** [comment]
closing issue as it's not an hackney issue per see.
