### ISSUE TITLE
%HTTPoison.Error{id: nil, reason: :closed}

### ISSUE THREAD

**Issue by ijunaid8989** [benoitc/hackney#398]
Hello, Everyone.

We are using HTTPoison in our code base for the post and get requests while using the hackney pool. Posting here is just because I want to get some opinions from all the experts.

We are working with a lot of cameras, where, from each camera, we are getting images, And then all those images, we are saving them to[ seaweedFS](https://github.com/chrislusf/seaweedfs) servers. 

We are making almost thousand of request on per second range. On the seaweedFS side, we have initiated the servers with a timeout of 10 seconds. And on our code base side, for uploading the image we are using this hackney configuration.
```
      :hackney_pool.child_spec(:seaweedfs_upload_pool, [timeout: 5000, max_connections: 1000]),
      :hackney_pool.child_spec(:seaweedfs_download_pool, [timeout: 5000, max_connections: 1000]),
```

For last few days, We are having an issue in this. At first, the timeout and max_connections on our side were 10 secs and 5K. And we started getting those HTTPoison errors as

```
{%HTTPoison.Error{id: nil, reason: :closed}}
```
The errors count was so high almost to 12K and so on, So for just for the time being, after discussing it in Elixir Slack channel I changed the timeout and max_connections to the above settings. After this, the errors reduced to 3K from 12K but only for 2 or 3 days, after that the error count is again going to 12K and so on. 

The person who developed SeaweedFS, Pointed that the library we are using to send HTTP requests is not closing the connections, And on our seaweedFS server side(the server to which our code base send requests for read and write) the result of this command is
```
root@Ubuntu-1404-trusty-64-minimal ~ # netstat | grep http | wc -l
5086
```

Can anyone suggest me something? What could be the reason of this error? 

I have done few discussions on Elixir Slack Channel and what I come to know, with hackney pool, If we are making a post request with a timeout of 5 seconds and the HTTP request returned with success within 2 or 3 seconds then the connection which was made for this request will be remain open for other 2 seconds(completing 5 seconds) so that, that still open connection could be used by other http post request? Maybe I am wrong in this theory.

But It will be nice if anyone will point me to some better solutions with hackney pool.

We are using HTTPoison 0.11.1 which eventually using hackney 1.7.1.

**Comment by mgumz** [comment]
@ijunaid8989 in general it is a good idea to keep long-standing connections (handled by a pool) because otherwise you will have some overhead (tcp handshake) + you will burn your sending ip:port for a while (30s+) since the kernel will not pick the same ip:port for a while (see TCP_WAIT). especially if you have a high rate of requests towards the other service, you will exhaust your available ip:port combination (remember, max 64k ports) quickly. so, to have a reasonable sized pool of standing connections (http keep-alive, the default with http1.1) is a good thing.

obviously, your current setup has problems. my suggestions: capture the traffic between your service and seaweedfs. find out, which side closes the connection (my guess: seaweedfs) and then look on that side (eg, out of file-handles etc).

i do not consider this issue here a problem of hackney and the issue should be closed as "unrelated".

**Comment by InoMurko** [comment]
So who keeps the connections open and makes the pid being reused? Is it the pools problem or the server? If it's the server, what should be setting on the server be?

We had so many problems with pooling in hackney that we decided to disabled them completely.

**Comment by benoitc** [comment]
this should have been fixed now.

**Comment by benoitc** [comment]
no answer since. closing issue then. feel free to reopen a new one if the problem still exists and hass not been reported since.

**Comment by archSeer** [comment]
@benoitc To add more info to the conversation: We have an internal service we're using via HTTP, and the server has a 10min timeout. We made a new pool for it and set the timeout to 550s to bring it just a bit under 10min.

`[pool: :conn_pool]`

```elixir
:hackney_pool.child_spec(:conn_pool, [timeout: 550_000, max_connections: 100]),
```

It seems to happen sporadically every 10mins (or more, our traffic varies during daytime, dropping off significantly during night time).

<img width="1136" alt="screen shot 2018-05-22 at 16 43 19" src="https://user-images.githubusercontent.com/1372918/40348802-3653da6a-5d94-11e8-957b-d11f0703204f.png">
