### ISSUE TITLE
"handshake failure" Erlang 19.3, CentOS 6.4, hackney 1.7.1

### ISSUE THREAD

**Issue by jyurek** [benoitc/hackney#406]
I'm trying to use hackney via HTTPoison in Elixir. I'm making an HTTPS request to a public URL. I get this in my logs:

    13:18:20.936 [warn] hackney_ssl: ECC not enabled
    13:18:21.110 [error] SSL: :certify: tls_connection.erl:715:Fatal error: handshake failure - malformed_handshake_data

If I change the URL I attempt to get to HTTP instead of HTTPS, it works, so it's not that there's a server problem. [Edit: Ok the same thing happens for `curl` so it might be a server problem, or at least a client machine problem.]

I'm willing to be told it's an openssl problem.

**Comment by alinpopa** [comment]
Getting exactly the same error (but on Erlang), and I'm having the following setup:
- Macos 10.12.4
- Erlang 19.3
- Tried using Hackney 1.6.5 and 1.8.0 (both raise the same error)
- Used the "Simple example" from the README https://github.com/benoitc/hackney#simple-request, so doing a request exactly like in that example, no funny business.

**Comment by benoitc** [comment]
@alinpopa looks at #387 for a solution to your issue.

@jyurek  I guess it's same issue, your openssl installation doesn't have curve ciphers which is detected by hackney there. Maybe the server you want to achieve needs them?

**Comment by benoitc** [comment]
@jyurek can you provide the url on which it happened?

**Comment by benoitc** [comment]
bump?

**Comment by jyurek** [comment]
Oh sorry. The URL is https://www.mbta.com/uploadedfiles/MBTA_GTFS.zip

**Comment by benoitc** [comment]
sorry for the late response :( I tested it with the latest version of hackney + certifi) on latest Erlang without reproducing it. Closing the issue then
