### ISSUE TITLE
Too many sockets in CLOSE-WAIT state

### ISSUE THREAD

**Issue by Zert** [benoitc/hackney#411]
I have a system which makes a large amount of async requests using hackney. Thank you for this library!
But I have a strange behaviour only for HTTP and not for HTTPS. When hackney works without default pool (proxy issues, btw), it does not close connection after request completion.

Script for this missbehaviour:

```
application:load(hackney).
application:set_env(hackney, use_default_pool, false).
application:ensure_all_started(hackney).

Url = "http://ipinfo.io/json".

Call = fun() -> {_, Ref} = hackney:get(Url, [], "", [{stream_to, self()}, async]), io:format("~p~n", [Ref]), timer:sleep(5000), flush(), hackney:close(Ref) end.

Call().
erlang:process_info(erlang:whereis(hackney_manager), links).

Call().
erlang:process_info(erlang:whereis(hackney_manager), links).

Call().
erlang:process_info(erlang:whereis(hackney_manager), links).
```

Each `Call()` adds one linked port to `hackney_manager`. These sockets are stuck in CLOSE-WAIT state and exhaust system limits. So I have to close them running external process each 10 minutes and calling `gen_tcp:close(Port)`

At the same time I don't see this behaviour for HTTPS (try with `Url = "https://ipinfo.io/json"`)

**Comment by Zert** [comment]
It seems sockets leak for HTTPS too, but linked with another process, not `hackney_manager`.
This is the `process_info` output of this process, if it can helps you (Elixir, sorry):
```
[registered_name: :tls_connection_sup,
 current_function: {:gen_server, :loop, 6},
 initial_call: {:proc_lib, :init_p, 5}, status: :waiting, message_queue_len: 0,
 messages: [],
 links: [#PID<0.25267.188>, #PID<0.20723.189>, #PID<0.29407.189>,
  #PID<0.6785.190>, #PID<0.19236.190>, #PID<0.11638.190>, #PID<0.2952.190>,
  #PID<0.23315.189>, #PID<0.27224.189>, #PID<0.26363.189>, #PID<0.22182.189>,
  #PID<0.11480.189>, #PID<0.16085.189>, #PID<0.18168.189>, #PID<0.20594.189>,
  #PID<0.17143.189>, #PID<0.12807.189>, #PID<0.15533.189>, #PID<0.5706.189>,
  #PID<0.10454.189>, #PID<0.8.189>, #PID<0.30923.184>, #PID<0.9516.188>,
  #PID<0.15303.188>, #PID<0.15909.188>, #PID<0.12633.188>, #PID<0.14739.188>,
  #PID<0.11336.188>, #PID<0.1030.188>, #PID<0.8947.188>, #PID<0.8117.188>,
  #PID<0.4794.187>, #PID<0.32121.187>, #PID<0.9572.186>, #PID<0.9839.170>,
  #PID<0.5142.176>, #PID<0.2772.184>, #PID<0.21976.184>, #PID<0.22017.177>,
  #PID<0.2725.184>, #PID<0.15503.174>, #PID<0.2813.175>, #PID<0.8898.171>, ...],
 dictionary: ["$initial_call": {:supervisor, :tls_connection_sup, 1},
  "$ancestors": [:ssl_connection_sup, :ssl_sup, #PID<0.980.0>]],
 trap_exit: true, error_handler: :error_handler, priority: :normal,
 group_leader: #PID<0.979.0>, total_heap_size: 53194, heap_size: 6772,
 stack_size: 9, reductions: 1325523,
 garbage_collection: [max_heap_size: %{error_logger: true, kill: true, size: 0},
  min_bin_vheap_size: 46422, min_heap_size: 233, fullsweep_after: 65535,
  minor_gcs: 105], suspending: []]
```

So, there is ports leakage somewhere in hackney :(

**Comment by benoitc** [comment]
I guess this is because the server send a keepalive, so the connection will be kept. Using `hackney:close/1` should fix it.

Let me know :)

**Comment by Zert** [comment]
> Using hackney:close/1 should fix it.

Yes, but it doesn't. My code sample has `hackney:close(Ref)`. I have this problem only in async mode.

**Comment by benoitc** [comment]
hrm I think you amso need to use `hackney:stop_async/1` but will try later in the day. Thanks for the feedback

**Comment by Zert** [comment]
Have no changes with `hackney:stop_async/1`

**Comment by Zert** [comment]
Hello, Benoit! Did you try it?

**Comment by benoitc** [comment]
@Zert sorry quite busy last week. I will have a look later tonight. Thanks for the patch anyway :)

**Comment by Zert** [comment]
Have no more problems on my production with this patch since yesterday

**Comment by benoitc** [comment]
fixed in latets master. Thanks for the patch @Zert
