### ISSUE TITLE
econnrefused for no reason

### ISSUE THREAD

**Issue by ngw** [benoitc/hackney#415]
I'm developing a Phoenix app using the oauth2 lib and I'm trying to authenticate against a Rails powered provider. 
The problem I'm facing is that I get an econnrefused for reasons I really can't understand.

    iex(3)> :hackney.request(:post, "http://127.0.0.1:3000/oauth/token", [], "client_id=2591bfa87c44ac8a2d9b6089c924be729ede5ffe639dc1cc2c2ecc6775cbbea7&client_secret=54a8ec90912eb9a89253d0618ef100e56a7ead455766d5295778a146f118558b&code=932e60aa42f2ff13a641b59d3b3a21d929c46e15dd16d62490609af16e8d8716&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fauth%2Ffitzdares%2Fcallback", [])
    {:error, :econnrefused}

This request  never hits the Rails server, it basically crashes before.
If I do the same with curl everything works as expected.

When I tried to gather more infos I had some messages about not having sockets in the pool, but I have no idea how to deal with this.

https://gist.github.com/ngw/c631ac1be3207614ea79671aa6a4f72c

Any suggestion? why Hackney fails with this simple POST req? TIA

**Comment by MSch** [comment]
@ngw we are seeing a similar problem, what version of hackney are you using?

**Comment by ngw** [comment]
Hi, I solved it, it was a misconfiguration of my linux machine

https://github.com/scrogson/oauth2/issues/94

**Comment by alecernas** [comment]
I have the same issue with my rails app
