### ISSUE TITLE
Feature request - Unix domain socket support 

### ISSUE THREAD

**Issue by binarytemple** [benoitc/hackney#418]
Unix domain sockets are very useful for communicating with the Docker daemon. The advantage is principally that you don't need to organize any authentication (generating certs, installing, restarting daemon, etc).  

When working with curl, it is possible to use the '--unix-socket' argument in order to use Unix domain socket. [Here](https://medium.com/lucjuggery/about-var-run-docker-sock-3bfd276e12fd) is an example which demonstrates communicating with the docker daemon using this mechanism.

Unix domain socket support has been introduced as of Erlang 19, not much documentation, but there is a thread on the Erlang list, [here](http://erlang.org/pipermail/erlang-questions/2016-October/090629.html)

I've extracted an example of communicating over Unix domain socket using UDP into this [gist](https://gist.github.com/binarytemple/568daf5c2abd11e5faedce5467ab1899).

Do you have any idea what it would take to get this working at present?

**Comment by benoitc** [comment]
@binarytemple there already limited support for it. <for calling unix socket in the current version you will need to use such uri: `http+unix://httpbin.sock/mypath`.

**Comment by binarytemple** [comment]
Ah, thanks. The conflation of the socket path and URL are kind of weird though. I mean taking this as an example:

```
curl -XPOST --unix-socket /var/run/docker.sock \
-d ‘{“Image”:”nginx”}’ \
-H ‘Content-Type: application/json’ \
http://localhost/containers/create
```
The socket path is : '/var/run/docker.sock' but the URL path is '/containers/create'.

Any suggestions?

**Comment by binarytemple** [comment]
(I've been reading through the integration tests btw ( hackney_integration_tests.erl )

**Comment by binarytemple** [comment]
Solution - URL encode the socket path. I considered modification, but it's much simpler just to go with it.
