### ISSUE TITLE
news/changelog is out of date

### ISSUE THREAD

**Issue by axelson** [benoitc/hackney#423]
Is it possible to get the `NEWS.md` file updated? It only lists releases up to 1.6.2 when the latest release is 1.8.6. The changelog is helpful for end users to understand new code that is being introduced when upgrading.

**Comment by benoitc** [comment]
Right. thanks for the report, I will take care about that in next major release. waiting for it there is always the commit log: https://github.com/benoitc/hackney/compare/1.6.2...master

**Comment by benoitc** [comment]
fixed in 305fbff4e92312bace149716a1d5afa44f70a68a

**Comment by axelson** [comment]
Fantastic, thanks!
