### ISSUE TITLE
Unknown CA while Proxying

### ISSUE THREAD

**Issue by dspencer001** [benoitc/hackney#424]
I am having an issue with proxying and verifying peers over ssl. When I make the request without the proxy it succeeds, when proxying it fails. I have this issue using squid and mitmdump. I am using HTTPoison, but the error happens as well when calling hackney directly. Any idea what's happening?

We are not using connection pools and have disabled the default pool.

EDIT: This is on hackney 1.8.0, I have tested on hackney 1.8.6 and had the same issue.
EDIT2: This is on elixir 1.3.4 and erlang 18.3

To replicate in IEx with Elixir with mitmdump running on port 8080:
`:hackney.request(:get, "https://search.atomicjoltbetaapps.com", [], <<>>, [{:proxy, "localhost:8080"}])`

That throws this error:

```
[error] SSL: :certify: ssl_handshake.erl:1490:Fatal error: unknown ca
{:error, {:tls_alert, 'unknown ca'}}
```

mitmdump shows this:
`<< Cannot establish TLS with client (sni: None): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert unknown ca')],)",)`

This is the trace:

```
[hackney trace 80 <0.7030.0> 2017:07:27 19:14:41 4982] request
   Content: [{module,hackney},
             {line,308},
             {method,get},
             {url,{hackney_url,hackney_ssl,https,
                               <<"search.atomicjoltbetaapps.com">>,<<"/">>,
                               <<"/">>,<<>>,<<>>,
                               "search.atomicjoltbetaapps.com",443,<<>>,<<>>}},
             {headers,[]},
             {body,<<>>},
             {options,[{proxy,<<"localhost:8080">>}]}]
[hackney trace 60 <0.7030.0> 2017:07:27 19:14:41 4982] HTTP proxy request
   Content: [{module,hackney},{line,617},{url,<<"localhost:8080">>}]
[hackney trace 60 <0.7030.0> 2017:07:27 19:14:41 4982] connect
   Content: [{module,hackney_connect},
             {line,33},
             {transport,hackney_http_connect},
             {host,"localhost"},
             {port,8080},
             {dynamic,true}]
[error] SSL: :certify: ssl_handshake.erl:1490:Fatal error: unknown ca

[hackney trace 80 <0.7030.0> 2017:07:27 19:14:42 4126] connect error
   Content: [{module,hackney_connect},{line,262}]
{:error, {:tls_alert, 'unknown ca'}}
```

**Comment by benoitc** [comment]
there is a new version of certs that is coming. I will check that in the morning. Thanks!

**Comment by dspencer001** [comment]
Why would it work without the proxy if it was a missing certs issue?

**Comment by dspencer001** [comment]
I updated the initial post with elixir and erlang version info.

**Comment by benoitc** [comment]
I missed the part with the proxy. It should be related to #355 . I will  have a look on it asap. probably over the week-end.

**Comment by dspencer001** [comment]
I actually ran into that issue previously when redirecting, so in my application I have disabled the default connection pool. If it is somehow trying to find a cert for localhost though that would explain why it can't find one.

**Comment by dspencer001** [comment]
So it turns out mitmproxy is inserting a cert, which is causing requests to fail when made through it. Squid though does not, and for some reason requests to https://search.atomicjoltbetaapps.com through it work now. I'm not sure what changed, but I'm fairly certain that it was nothing with hackney. Given that I can't replicate the issue anymore with squid, and mitmproxy is failing correctly due to the self signed cert, I'm closing this. If I can encounter it again I will try to get more information and reopen it.

**Comment by benoitc** [comment]
thanks for the feedback @dspencer001
