### ISSUE TITLE
Noobish runtime question

### ISSUE THREAD

**Issue by paul-bell** [benoitc/hackney#428]
Hello,

Several years ago I knew barely enough Erlang to write some lengthy programs. But they were all simple, one module affairs. Since then I've done nothing with Erlang but am trying to get back into it.

I successfully (I think) built hackney using rebar3. I then started a shell via the _erl_ command. Following some examples I found on the Web, I did this:
```
application:ensure_all_started(hackney).                   
{error,{hackney,{"no such file or directory", "hackney.app"}}}
```
So I added to the runtime path and tried again:
```
code:add_patha("C:/erl9.0/usr/hackney/_build/default/lib/hackney/ebin").
application:ensure_all_started(hackney).                                
{error,{idna,{"no such file or directory","idna.app"}}}
true
```
You can see where this is going: I ended up adding to runtime path the _ebin_ directory for each of the apps that constitute hackney. I should point out that in the rebar3 shell, I had no such problem, i.e., the initial application:ensure_all_started/1 magically incorporated/resolved all the apps.

I realize that this question is not specific to hackney. But I'm hoping it's so simple a matter to fix that someone can easily show me what I am doing wrong.

Thank you for your help.

-Paul

**Comment by benoitc** [comment]
sorry for the late answer. if you want to have hackney and its dependencies loaded , the easiest way is to use `rebar3 shell` in your application. It will do the work for you. Also don't forget to add hackney to the applications lists in you `.app.src` file.

**Comment by paul-bell** [comment]
Thanks very much for your reply.
I had no idea that I could use the rebar3 shell in my application.
