### ISSUE TITLE
Why 307 POST redirects are not followed?

### ISSUE THREAD

**Issue by orestis** [benoitc/hackney#429]
By my understanding of https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307 , there's no reason to not follow a 307 redirect even with a POST method (and should explicitly preserve the method).

I can't figure out a way to make hackney (used via HTTPoison) to explicitly follow a 307 redirect (vs returning a `:maybe_redirect` `AsyncResponse`).

**Comment by benoitc** [comment]
You can set force_redirect to true. It should work. If not please post me the log so I can have a closer look.
