### ISSUE TITLE
ca authority error

### ISSUE THREAD

**Issue by smokinguns** [benoitc/hackney#431]
First off, great library. Longtime developer, but still new on the erlang and elixir front. 
I see where you can pass in the ca authority as a file path, which seems to get me past the unknown ca authority error. My question is why the use of certifi, when it looks like erlang ssl server has an option to verify the ca authority as well as configure the vm from the command line to look at the correct cacertfile. I'm sure there are other use cases then mine, so an explanation will do.  I was hoping to avoid worrying about setting the ca authority all together, but that doesn't seem possible without erlang able to look in a common place. Do you know how others have solved this? We seem to like httpoison and hackney.

**Comment by ericmj** [comment]
How do you configure the VM to find a cacertfile?

**Comment by benoitc** [comment]
@smokinguns certifi makes it easy to use the official bundle from mozilla to check the certificate. Plus it will cache it in the heap and allows you to use it via an escript.

Otherwise you will have to get it by yourself and cache it . Which is still possible in hackney by using the ssl options :)

**Comment by smokinguns** [comment]
ok, l'm still somewhat of a noob in reading elrang...and well bouncing between both erlang and elixir can be a little taxing at first. We are unfortunately stuck behind a firewall that carries out an allowed man in the middle attack, so we will need to validate our cert, not the mozilla cert. I appreciate all the work that has been done on the repo. Also, thanks for taking the time to respond.

**Comment by benoitc** [comment]
@smokinguns  like i said you can pass any ssl options even your own ca to hackney in ˋssl_options`. it will replace the defaults.

**Comment by benoitc** [comment]
https://github.com/benoitc/hackney/blob/master/doc/hackney.md#request-5
