### ISSUE TITLE
Documentation: too many pending clientrefs unless you use hackney:body.

### ISSUE THREAD

**Issue by javobalazs** [benoitc/hackney#435]
This is not a bug but something that should be emphasized in the documentation. The case: it seems a bit strange but in a certain project we simply discarded what was returned from `hackney:request` (actually, `:hackney.request` because it was an Elixir-project). This was something like a keep-alive, and the result (or whether it was successful at all) was not interesting. A certain dedicated process was making the calls periodically. After a while it simply wouldn't work, and performing a hand request reported timeout. It took a while for us to realize that we should use `hackney:body` (`:hackney.body`) to read out the resulting clientrefs to get them freed, otherwise they stack up, tying up even more other resources. The actual reported error ("timeout") wasn't informative, and it took a day for us to get the real reason. We were stupid, I know, but anyway, this should be in the documentation, or the error report should be more informative.

**Comment by benoitc** [comment]
@javobalazs I agree. The way keepalive will be handled in the month release will make it more explicit. Thanks for the feedback!

**Comment by benoitc** [comment]
fixed in latest versions.
