### ISSUE TITLE
Anyway to get rid of content-type and content-length in every form data field for multipart

### ISSUE THREAD

**Issue by yyzzz6000** [benoitc/hackney#437]
Hi,
I met an issue when uploading a file to a cloud service by posting form data because the request includes content-type: application/octet-stream and content-length: xxx for each form data field. 
<img width="1342" alt="screenshot 2017-09-23 13 31 28" src="https://user-images.githubusercontent.com/11425534/30777839-387b7132-a079-11e7-824d-4d6bcc980d59.png">
Is it possible to get rid of them? They seem not necessary for a form data field.
according to RFC 1867:
https://www.ietf.org/rfc/rfc1867.txt

   Suppose the server supplies the following HTML:

     <FORM ACTION="http://server.dom/cgi/handle"
           ENCTYPE="multipart/form-data"
           METHOD=POST>
     What is your name? <INPUT TYPE=TEXT NAME=submitter>
     What files are you sending? <INPUT TYPE=FILE NAME=pics>
     </FORM>

   and the user types "Joe Blow" in the name field, and selects a text
   file "file1.txt" for the answer to 'What files are you sending?'

   The client might send back the following data:

        Content-type: multipart/form-data, boundary=AaB03x

        --AaB03x
        content-disposition: form-data; name="field1"

        Joe Blow
        --AaB03x
        content-disposition: form-data; name="pics"; filename="file1.txt"
        Content-Type: text/plain

         ... contents of file1.txt ...
        --AaB03x--

**Comment by benoitc** [comment]
Closing the issue. With ef3a9fb43b8786d85f402389e0cec3cc7fa0a467 you can post a file with a different multipart header.
