### ISSUE TITLE
Remove 0.10.0 from hex

### ISSUE THREAD

**Issue by scohen** [benoitc/hackney#448]
I think the memory leak is severe enough to warrant retiring that version.
`mix retire hackney 0.10.0 invalid` should do it.

**Comment by benoitc** [comment]
there is not such command in rebar3 unfortunately cc @tsloughter i will try to do that with another user on my machine (last time mix had overwritten the local hex conf ...)

**Comment by benoitc** [comment]
a little too late and didn't want to fight once again with mix to do it :) I wish it could be easier....

So let's close that ticket latest release is now 0.11.0 anyway :)
