### ISSUE TITLE
case_clause issue on cancel_checkout

### ISSUE THREAD

**Issue by byronpc** [benoitc/hackney#452]
I'm receiving this crash on my server

`{case_clause,0},[{hackney_pool,handle_cast,2,[{file,"src/hackney_pool.erl"},{line,312}`

Not sure if this is related to a memory leak we're experiencing when this crash occurs.

Upon checking the code, I can see `del_from_queue` can return `{Queues, 0}` where 0 is supposed to be a boolean for `Removed`. I think it should be `false` right?

**Comment by byronpc** [comment]
@jimdigriz

**Comment by jimdigriz** [comment]
Eugh, badly refactored, sorry!

When I moved from passing back an integer to a boolean I forgot to fix up the `error` path.  Can you try https://github.com/benoitc/hackney/pull/453

**Comment by byronpc** [comment]
@jimdigriz there seems to be an issue with checkout_cancel in general. I'm not sure where but it seems to get stuck in the messagequeue of the pool from time to time causing all succeeding checkouts to the pool to fail.

**Comment by jimdigriz** [comment]
...stuck for ~8 seconds (the default for `connect_timeout` unless you have it set to something else) before being immediately replaced with new `checkout_cancel` cast message?

**Comment by byronpc** [comment]
the thing is, i'm not sure if the message queue stacking up happens because of load. If it is because of load, I will occasionally see the message queue warnings and timeouts growing. But in this case it happens only once in a while (like once in an hour or so) but when it happens, all succeeding calls will timeout (like i get thousands of timeouts and only lasts for around 2 seconds) and the message queue error will be full of checkout_cancel messages and seems lots of calls to `del_from_queue`, then it will recover. Again, I'm not sure what happens internally but this is my observation. The issue may be from another place that holds up the gen_server and the `checkout_cancel` messages are only a side effect. Will look more into this.

**Comment by jimdigriz** [comment]
@byronpc how do you expect hackney to behave if you have a connect timeout set to (for example) 8 seconds, the pool size limited to 10 and the response timeout set to 60 seconds?  What should hackney do if the upstream HTTP server, given these constraints you may have set, takes 30 seconds to reply whilst you are sending ~100 requests per second?

The problem is the *upstream* HTTP server is under load and struggling, not hackney.

**Comment by jimdigriz** [comment]
@byronpc did the https://github.com/benoitc/hackney/pull/453 fix the `case_clause` for you?
