### ISSUE TITLE
Hackney halts code_server

### ISSUE THREAD

**Issue by scohen** [benoitc/hackney#458]
Hackney has several issues that will absolutely destroy an erlang distribution. The worst is that it recompiles its metrics module whenever a connection is created. This is incredibly expensive operation that requires that all processes wake up and handle a message, and reply to it. The code server will not continue until all messages are received from all processes. This can take a long time on VMs with a lot of processes. 

I cannot understand why recompilation happens when connections are created. The only thing that I can think of is that you could change the metrics module at runtime, but that won't take effect immediately, only after all connections have been cycled. The PR below moves this recompilation to application start. If you want to swap out metrics modules, I recommend having a function that does the recompilation and then updates the application variable. 

These issues are fixed in https://github.com/benoitc/hackney/pull/457

**Comment by benoitc** [comment]
I agree it shouldn't rebuild the module each time, sounds like a bug in metrics. I will release today with your fix and revisit later the update to latest version of metrics that should fix it.

**Comment by scohen** [comment]
👍

**Comment by benoitc** [comment]
@scohen 0.11.0 is out with your fix. Sorry for the delay ....

**Comment by scohen** [comment]
No problem, glad it's in there!
