### ISSUE TITLE
Document the use of basic_auth option

### ISSUE THREAD

**Issue by nlfiedler** [benoitc/hackney#459]
The `basic_auth` option does not appear in the documentation, but searching the repo I can find the test code example. That works, but having its usage mentioned in the docs would be ideal.

**Comment by paulo-ferraz-oliveira** [comment]
You have this, these days:
```
* `{basic_auth, {binary, binary}}`: HTTP basic auth username and password.</li>
<li>`{proxy, proxy_options()}`: to connect via a proxy.
```

Is that the doc. you mention should exist? (this is `hackney.md`)

**Comment by nlfiedler** [comment]
Yes, thanks.
