### ISSUE TITLE
Metrics: Request vs. Response Timings

### ISSUE THREAD

**Issue by GalaxyGorilla** [benoitc/hackney#461]
Hey, I just wrapped my head around to get the difference between `request_time` and `response_time`. Can someone explain that? From the code ist seems to be non-trivial to see what `request_time` is about.

**Comment by benoitc** [comment]
Sorry for the late response,

`request_time` is measuring the time a complet request takes including the response where the `response_time` only measures the time took to receive the response after the request has been sent.
