### ISSUE TITLE
Empty response body when Content-Length and Transfer-Encoding headers are omitted

### ISSUE THREAD

**Issue by jknipp** [benoitc/hackney#475]
Beginning with v1.11.0, if the response from the server omits both the `Content-Length` and `Transfer-Encoding` response headers, the body of the response is not parsed and returned.

### v1.11.0 Response Body

<img width="983" alt="screen_shot_2018-02-14_at_10_40_38_am" src="https://user-images.githubusercontent.com/84280/36216631-ee447290-1174-11e8-8dba-88aba95d57b0.png">

### v1.10.1 Response Body

<img width="997" alt="screen_shot_2018-02-14_at_10_45_46_am" src="https://user-images.githubusercontent.com/84280/36216617-e4b79fb8-1174-11e8-8826-ce861bcf3d9c.png">

I believe the bug was introduced with the change in https://github.com/benoitc/hackney/pull/450 to handle empty/invalid content-length.

https://github.com/benoitc/hackney/commit/5b51fb82547dd3a492aaac5d63f7aa1ada1e65cf#diff-03059c69a9df088e2476724af69f06bdL334

**Comment by AnilRedshift** [comment]
This is a breaking bug for us, we've had to pin our hackney at an old version to mitigate it.

**Comment by ConnorRigby** [comment]
I just ran into this issue also with `Httpoison`

**Comment by benoitc** [comment]
@jknipp good catch! 

Is the server sending an HTTP 1.0 response ? 1.1 normally expects to have a content length. Can you check it?

I propose indeed to fix it by checking if the client receive an http 1.0 response and then read until a max. Thoughts?

**Comment by AnilRedshift** [comment]
@benoitc: Unfortunately, a lot of the internet doesn't follow specifications (HTTP 1.1 or otherwise). It would be beneficial for a client library to be as flexible as possible in this regard.

The spec actually doesn't require Content-length to be set. Instead, if the header is not sent, then the client must close the connection after it is completed.

**Comment by benoitc** [comment]
this is only for backward compatibility. I will only set a max to receive then. Fix release will land today.

**Comment by ericmj** [comment]
The server is following the spec, as @AnilRedshift a missing content-length is valid and closing the connection will signal the end of the response body.

**Comment by benoitc** [comment]
well the server should do its best to send a content-length. I will fix it anyway.

**Comment by benoitc** [comment]
can you test #481 ? It shoudl fix your issue. Let me know :)

**Comment by PatNowak** [comment]
Hi,

I just tested. Value in response is correct, but the whole response is returned as an "error response". I use email decryptor service, so body returned is an email. 
Please take a look:

Response from `hackney` 1.10.0 via HTTPoison (default use case)

	{:ok,
		%HTTPoison.Response{
		body: "[\"empty11@o3.pl\"]", 
		headers: headers,
		request_url: "URL",
		status_code: 200
	}}

Response from `hackney` 1.11.0 (master) via HTTPoison - reason for this issue

	{:ok,
		%HTTPoison.Response{
		body: "",
		headers: headers,
		request_url: "URL",
		status_code: 200
	}}

Response from `hackney` from branch `fix/gh-475` via HTTPoison

    {:error, %HTTPoison.Error{id: nil, reason: {:closed, "[\"empty11@o3.pl\"]"}}}

Response from `hackney` from fix branch 

    {:ok, 200, _list, ref} = :hackney.request(:get, url, headers) # that's fine
     :hackney.body(ref)
    {:error, {:closed, "[\"empty11@o3.pl\"]"}}
     
As you may see, the value is correct, but returns in error response.

**Comment by PatNowak** [comment]
It was url from private network, so it will not work for you. I can find an example that will be available publicly :)

**Comment by benoitc** [comment]
@PatNowak I pushed ce32d21fa3fe4b9fb64d8d44a158181eb4aa40e8 in the PR that should fix your issue. Let me know :)

**Comment by benoitc** [comment]
@PatNowak ?

**Comment by benoitc** [comment]
bump.

**Comment by filmor** [comment]
@benoitc, in the meantime, would you please retract the package from Hex?

**Comment by benoitc** [comment]
@filmor Only mix has this feature. Anyway did you test the PR, it would help to have some feedback...

**Comment by filmor** [comment]
I think you can ping the hex admins (support@hex.pm), I'll test the PR on Monday.

**Comment by benoitc** [comment]
@filmor ping?
