### ISSUE TITLE
Unexpected message when using async once

### ISSUE THREAD

**Issue by critch** [benoitc/hackney#479]
I wrote a very simple test case in elixir. From best I can tell, my example is nothing more than your documented async example, just with stream_next called to handle the once argument, and a timer.sleep of about 1000 to simulate a work load being made on the results. 

Best I can guess, there must be a race condition that is easier to cause when there is a sufficiently large delay between the stream_next calls. I'm guessing the socket has sent all the data, and closed before our last call to stream_next.

This was tested with the 1.11 release.

**Comment by critch** [comment]
This may be related to #464

**Comment by benoitc** [comment]
can you try #482 ?

**Comment by critch** [comment]
As a bit of help, I modified the 3 instances of the unexpected message logs and found this one is on line 151.

**Comment by rozap** [comment]
I'm observing the same thing. I've tried #482 but it doesn't seem to do the trick. I'll continue looking at what's going one.

**Comment by benoitc** [comment]
should be fixed in latest master.

**Comment by critch** [comment]
finally able to test. So far it does appear to be fixed. Tried with a 10mb file using a 1 second delay in between messages. No issues.

Thank you for your effort.
