### ISSUE TITLE
How to implement always connected client?

### ISSUE THREAD

**Issue by artempankov** [benoitc/hackney#483]
i need always opened connection to https server to reduce latency on connection opening when i make request

it looks like hackney sometimes reconnects sockets:

```
[hackney trace 60 <0.8125.1> 2018:02:28 09:30:16 4265] reuse a connection 
   Content: [{module,hackney_connect},{line,189},{pool,first_pool}]
```

but sometimes not:
```
[hackney trace 80 <0.8125.1> 2018:02:28 09:44:08 4229] no socket in the pool 
   Content: [{module,hackney_connect},{line,200},{pool,first_pool}]
[hackney trace 80 <0.8125.1> 2018:02:28 09:44:08 4336] new connection 
   Content: [{module,hackney_connect},{line,249}]
```

i have tried to reuse connection manually but with no success, after second sleep there is no socket for reusing:

```
    url = "https://api..com/api/v1/info"
    headers = []
    payload = ""
    options = []

    start = :os.system_time(:milli_seconds)
    {ok, status_code, _, client} = :hackney.request(method, url, headers, payload, options)
    {ok, body} = :hackney.body(client)
    IO.puts(:os.system_time(:milli_seconds) - start)

    :timer.sleep(1_000_000)

    transport = :hackney_ssl
    host = "api..com"
    port = 443
    options = []
    {ok, conn_ref} = :hackney.connect(transport, host, port, options)

    :timer.sleep(1_000_000)

    req_body = ""
    req_headers = []
    next_path = "/api/v1/info"
    next_method = :get
    next_req = {next_method, next_path, req_headers, req_body}

    start = :os.system_time(:milli_seconds)
    {ok, status_code, _, conn_ref} = :hackney.send_request(conn_ref, next_req)
    IO.puts(:os.system_time(:milli_seconds) - start)
```

which is the best way to ensure that socket is always connected? may be some manual check for socket status and manual reconnecting?

**Comment by benoitc** [comment]
HTTP 1.1 doesn't support aan always connected client by itself. Hackney handle keepalive but you need to manage reconnection when the server close the connection and/or to make sure to send a message to the server before the connection close. 

If the connection close you will get a timeout or close message and can probably reconnect from it or now. I will thinkj to add such feature soon.

**Comment by as-gennadiy-n** [comment]
@benoitc How could we receive in background a message about the server closing the connection? We'd like to reconnect at the moment when the connection is closed but not when our request is unsuccessful. Could you please share some examples or help us to build such behaviour using hackney?

**Comment by benoitc** [comment]
that's not easy todo for now. What you can do is to retrieve the socket using `hackney:request_info/1` and give the control of  the socket in active mode to another process and possibly wait for the closed message.

next version of hackney will handle pre-connections btw.

**Comment by benoitc** [comment]
Closing the issue since no answer since. you can see an example there: https://github.com/benoitc/hackney_pooler btw.
