### ISSUE TITLE
Hackney does not compile because of "certifi" dep (undefined parse transform 'ct_expand')

### ISSUE THREAD

**Issue by nicolasmd87** [benoitc/hackney#484]
DEPEND certifi.d
ERLC   certifi.erl
src/certifi.erl: undefined parse transform 'ct_expand'

**Comment by benoitc** [comment]
is this with erlang or elixir?

**Comment by nicolasmd87** [comment]
erlang

**Comment by benoitc** [comment]
the ci pass though. Which version are you using?

**Comment by nicolasmd87** [comment]
Hackney - master 
Erlang - OTP 20

**Comment by benoitc** [comment]
I don’t reproduce it. can you describe the steps you use to compile it?

**Comment by nicolasmd87** [comment]
I'm using erlang.mk and using hackney as a dep on the makefile of my app, it was working fine and then when I deleted the deps and brought them back hackney was throwing that error on compile.

**Comment by fenollp** [comment]
Fixed on mentioned PR.

**Comment by essen** [comment]
@nicolasmd87 As a workaround for now you can add the certifi version you want as a `BUILD_DEPS` of your top level project and I'll have a fix up in a few days.

**Comment by nicolasmd87** [comment]
Thx already did :) , using certifi Tag 2.2.0

**Comment by essen** [comment]
Most recent Erlang.mk can now build hackney again. To update Erlang.mk you can run `make erlang-mk`. Cheers!

**Comment by nicolasmd87** [comment]
Thx , cheers !

**Comment by jakubpawlowicz** [comment]
Got the same problem today with Elixir 1.5, hackney 1.15.1, and certifi 2.5.1 (but also 2.4.2). Turns out it was a missing `build_embedded: Mix.env == :prod` in `mix.exs`. Posting it here as it may help someone as this issue is a top hit (and only 1 of 2) for `undefined parse transform 'ct_expand'`.

**Comment by garthk** [comment]
For anyone else Googling this one after running into trouble switching Elixir releases, try:

```bash
rm -rf ~/.cache/rebar3 _build deps
mix deps.get
mix deps.compile
```

If you're using VS Code with the `jakebecker.elixir-ls` extension, shut it down and add `.elixir_ls` to the `rm` arguments.
