### ISSUE TITLE
switch between interfaces

### ISSUE THREAD

**Issue by artemk** [benoitc/hackney#486]
is there any possibility to use specific interface that are available in system? For instance I have 30 interfaces with different ip assigned to it. Can I manually set what interface to use for request. Thanks.

**Comment by benoitc** [comment]
You can do it using the `connect_options` setting that accepts soem of the `inet:setopts` / `gen_tcp:connect/2` options: 

http://erlang.org/doc/search/?q=inets%3Asetopts&x=0&y=0

Hope it helps.
