### ISSUE TITLE
Deadlocks in `hackney_manager:wait_async_response`

### ISSUE THREAD

**Issue by obmarg** [benoitc/hackney#498]
I'm seeing deadlocks in `hackney_manager:wait_async_response` with the latest master branch of hackney.

The stack trace of the hackney_manager process is:
![image](https://user-images.githubusercontent.com/556490/38254061-295bb162-3750-11e8-929f-4b10ec770448.png)

I can reproduce this fairly consistently in the tests for a couple of private projects, but dont have an easy code sample to reproduce it.

I believe what's happening is:

1. [Hackney monitors the stream process](https://github.com/benoitc/hackney/blob/master/src/hackney_manager.erl#L562)
2. It receives an exit message in monitor_child, and listens for DOWN messages.
2. [It receives a down noproc message from the monitor](https://github.com/benoitc/hackney/blob/master/src/hackney_manager.erl#L549-L550)
3. It enters wait_async_response, to wait for a down message.
4. That message never arrives, because it's already been read in monitor_child.

I've tried just removing the inner receive block from `monitor_child` and this stops the issue from occurring.  However, I assume that block is there for a reason and I'm not sure what other impact removing it has...

**Comment by obmarg** [comment]
I'd be happy to give you access to the repository with my failing tests if it'd help, but they do require a kubernetes cluster to run, so might be more hassle than it's worth.

Here's the diff that I changed:

```
diff --git a/src/hackney_manager.erl b/src/hackney_manager.erl
index 591a6cb..1c3a8b0 100644
--- a/src/hackney_manager.erl
+++ b/src/hackney_manager.erl
@@ -542,15 +542,8 @@ monitor_child(Pid) ->
   unlink(Pid),

   receive
-    {'EXIT', Pid, Reason} ->
-      receive
-        {'DOWN', _, process, Pid, normal} ->
-          ok;
-        {'DOWN', _, process, Pid, noproc} ->
-          ok;
-        {'DOWN', _, process, Pid, _} ->
-          {error, Reason}
-      end
+    {'EXIT', _Pid, _Reason} ->
+          ok
   after 0 ->
           ok
   end.
```

Not at all sure it's the correct fix, but I have run 170000 requests without hitting the same deadlock after that change.

**Comment by benoitc** [comment]
@obmarg can you try #499 and let me know?

**Comment by benoitc** [comment]
1.12.1 has been released. Thanks for the help!
