### ISSUE TITLE
./rebar eunit fails on Master (e6d84f40a4d2d650659ac54dba99c0bcbbb86af4)

### ISSUE THREAD

**Issue by ruanpienaar** [benoitc/hackney#501]
```
rebar3 eunit
```

```
module 'hackney_integration_tests'
  *** instantiation of subtests failed ***
**in function hackney_integration_tests:get_request/0 (/Users/ruanpienaar/code/hackney/_build/test/lib/hackney/test/hackney_integration_tests.erl, line 51)
in call from hackney_integration_tests:all_tests/0 (/Users/ruanpienaar/code/hackney/_build/test/lib/hackney/test/hackney_integration_tests.erl, line 7)
in call from hackney_integration_tests:'-http_requests_test_/0-fun-0-'/1 (/Users/ruanpienaar/code/hackney/_build/test/lib/hackney/test/hackney_integration_tests.erl, line 40)
**error:{badmatch,{error,econnrefused}}
```

**Comment by benoitc** [comment]
Not sure to follow, you can safely ignore this error, the test suit will finish normally with all tests pass:

<img width="1046" alt="screen shot 2018-04-20 at 19 02 13" src="https://user-images.githubusercontent.com/14498/39064060-5971f2aa-44cd-11e8-926e-44e3c7ea7090.png">

There is no plan yet to have integration tests work outside of the CI for now.

**Comment by ruanpienaar** [comment]
ok :) was just wondering whether you could maybe write a little erlang webserver or some easier fixture to show what exactly is being tested.

**Comment by benoitc** [comment]
@ruanpienaar i did that in the past: https://github.com/benoitc/echohttp maybe we should put it back?

**Comment by ruanpienaar** [comment]
Cool! i'll have a look

**Comment by benoitc** [comment]
closing the issue now as no move has been made.. I will accept any PR replacing httpbin anyway.
