### ISSUE TITLE
Use of TEST environment variable conflicts with other projects

### ISSUE THREAD

**Issue by eproxus** [benoitc/hackney#502]
In [`rebar.config.script` on line 24](https://github.com/benoitc/hackney/blob/e6d84f40a4d2d650659ac54dba99c0bcbbb86af4/rebar.config.script#L24) the environment variable `TEST` is used for something. In our make system we use the same environment variable to select test cases to run. When we included Hackney as a dependency, this broke the build because the `rebar.config.script` could not handle the value we set.

I argue that using the generic environment variable `TEST` in such a way is problematic because it hinders usages in other projects where this common variable name is used for other things. I suggest using a variable name unique to Hackney that doesn't run a high chance of conflicting with usage in other projects.

**Comment by benoitc** [comment]
I think TEST is also a variable used by travis but I maybe wrong. In any case I'm not sure we still need to have that `rebar.config.script` . I will check, thanks!

**Comment by paulo-ferraz-oliveira** [comment]
`rebar.config.script` no longer present. This can be safely closed.

Mentions to `TEST` are:
* `.travis.yml`: it's possible it'll go away soon,
* `hackney.http`: but `rebar3/eunit` already defines that.

**Comment by benoitc** [comment]
true. closing the issue
