### ISSUE TITLE
{:error, %HTTPoison.Error{id: nil, reason: "closed"}}

### ISSUE THREAD

**Issue by lypborges** [benoitc/hackney#503]
I’m getting a strange error in HTTPoison. When I do two request to a server “A” in the second I get connection close.

```
HTTPoison.get("http:/urla.com", [], [ ssl: [{:versions, [:'tlsv1.2']}] ,  hackney: [pool: :mypool],  max_connections: 1000])
```

 When I do this with other server it works. 

```
HTTPoison.get("http:/google.com", [], [ ssl: [{:versions, [:'tlsv1.2']}] ,  hackney: [pool: :mypool],  max_connections: 1000])
```
So I think it was a error on the server “A” , so a did a manual call with curl 20 times and all work perfect in the server “A” and “B”.

```
curl http://urla.com\?\[1-20\]
``` 
I tried with the default options and with the options above `[ ssl: [{:versions, [:'tlsv1.2']}] ,  hackney: [pool: :mypool],  max_connections: 1000]`. But I get the same error.
Any tip what could be the error?

**Comment by dkuku** [comment]
I got the exact same problem with HTTPPoison and I tracked it to hackney

```
iex(0)> :hackney.get "https://www.sejm.gov.pl/"
{:error, :closed}

iex(1)> System.cmd("curl", ["https://www.sejm.gov.pl/"])
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
100 16314  100 16314    0     0  16905  

```
I raised also an issue in HTTPPoison that it should handle it better: https://github.com/edgurgel/httpoison/issues/432

**Comment by benoitc** [comment]
update to latest certifi.... also ensurz to use latest version of hackney.
