### ISSUE TITLE
hackney:request throws error not mentioned in spec when app was not started

### ISSUE THREAD

**Issue by RodionGork** [benoitc/hackney#508]
Hi Friends!

This is not crucial, but `hackney:request(...)` throws error like `{error, badarg, [...]}` if the hackney was not started due to some reason. However this can be either added to spec, or caught and converted to something like `{error, not_started}` as return value. This will also help to make the library more "dialyzer-friendly". Current workaround is to place "catch" before call :)

**Comment by benoitc** [comment]
Hrm I think the erlang error may be more useful than returning an error. Imo this error must not be expected. What was your issue with it?

**Comment by benoitc** [comment]
Discussion ended a long time ago. I am closing the issue then. As a side note, having such error would imply to check if hackney is started or not to return it. I think the current message is OK somehow since it is very unexpected the application have not been started.
