### ISSUE TITLE
Question: graceful shutdown for supervised connection pool

### ISSUE THREAD

**Issue by jeffrom** [benoitc/hackney#518]
Sorry if this is already answered elsewhere, but what happens to a supervised pool when it's application is stopped and there are active connections in progress? Will they be allowed to complete or are they killed mid-request? 

the `:gen_tcp` documentation says:

```
How == write means closing the socket for writing, reading from it is still possible.

If How == read or there is no outgoing data buffered in the Socket port, the socket is shut down immediately and any error encountered is returned in Reason.

If there is data buffered in the socket port, the attempt to shutdown the socket is postponed until that data is written to the kernel socket send buffer. If any errors are encountered, the socket is closed and {error, closed} is returned on the next recv/2 or send/2.
```

This doesn't quite answer my question, as an HTTP request includes a send and a receive. Trying this out in console, it looks like the request does not complete. just want to confirm.

Thanks for all your work!

**Comment by benoitc** [comment]
I will close this issue, sorry for the delay to take care of it. As a short response, requests are not owned by gunicorn, so it will depends on your application. If you supervise each requests then you can probably gracefully stop each of them. However sockets idling in the pool are closed immediately.
