### ISSUE TITLE
rapid requests get deadlocked

### ISSUE THREAD

**Issue by seanmcevoy** [benoitc/hackney#525]
in our app we set up an application level session with a server (freshchat.com) and then in a short space of time make multiple http post calls to send it some relevant info.
every so often our automatic tests seems to cause a deadlock and we think it might be in the hackney client. the deadlocked processes look like the one below with a hackney record in the process dictionary that has no corresponding record in the hackney_manager ets table.

we're using hackney 1.6.0, is this a known issue? maybe it's been fixed in a later release?

rp(process_info(list_to_pid("<0.27622.43>"))).
[{current_function,{gen,do_call,4}},
 {initial_call,{proc_lib,init_p,5}},
 {status,waiting},
 {message_queue_len,0},
 {messages,[]},
 {links,[<0.27612.43>,<0.186.0>]},
 {dictionary,[{'$ancestors',[<0.27612.43>,<0.26314.43>,
                             <0.26268.43>,chat_supervisor_pool_2,
                             chat_supervisor_pool_worker_sup,chat_supervisor_pool,
                             sidejob_sup,<0.175.0>]},
              {#Ref<0.0.8912897.143182>,
               {client,undefined,
                       {metrics_ng,metrics_dummy},
                       hackney_ssl_transport,"web.freshchat.com",443,
                       <<"web.freshchat.com">>,[],nil,nil,#Ref<0.0.8912897.143182>,
                       true,hackney_pool,5000,false,5,false,5,nil,nil,nil,
                       undefined,start,nil,normal,false,false,false,undefined,
                       false,nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,
                       nil,undefined,nil}},
              {'$initial_call',{gen_py_amqp,init,1}}]},
 {trap_exit,true},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<0.174.0>},
 {total_heap_size,13544},
 {heap_size,6772},
 {stack_size,82},
 {reductions,14430},
 {garbage_collection,[{min_bin_vheap_size,46422},
                      {min_heap_size,233},
                      {fullsweep_after,10},
                      {minor_gcs,5}]},
 {suspending,[]}]

**Comment by seanmcevoy** [comment]
ah, this looks like a duplicate of issue #462

**Comment by benoitc** [comment]
do you mean you still reproduce it?

**Comment by seanmcevoy** [comment]
we reproduced this yesterday on 1.6, upgraded to 1.13 today and haven't seen it yet, though only running a few hours so that isn't unusual.
will re-activate this thread if it reproduces with 1.13, though i'm fairly confident that it won't. the fix for 462 seems to have it convered.

PS. thanks for hackney!
