### ISSUE TITLE
stats error, and overload instability

### ISSUE THREAD

**Issue by seanmcevoy** [benoitc/hackney#541]
when i overload a hackney pool i can reproduce some instability, generating large message queues in the pool process. eg, with a pool size of 50 and 1,000 workers making repeated requests i can see this output:

{hackney_pool:get_stats(default),process_info(proplists:get_value(default,ets:lookup(hackney_pool,default)),message_queue_len)}.
{[{name,default},
  {max,50},
  {in_use_count,50},
  {free_count,0},
  {queue_count,3492}],
 {message_queue_len,451}}

here the sum of in_use, free & queue should obviously be a maximum of 1000.

**Comment by seanmcevoy** [comment]
this may also help with issue: https://github.com/benoitc/hackney/issues/510

**Comment by Hinidu** [comment]
Thanks!
By the way, I’ve tested this patch yesterday evening and it didn’t help me too much. Our application still becomes unresponsive after heavy load if pool is enabled, but everything seems ok if pool is disabled.
I will continue my investigations.

**Comment by benoitc** [comment]
@Hinidu if you have a way to reproduce your issue please open a ticket. ALso check if the request are correctly closed so the connection is released to the pool.
