### ISSUE TITLE
connections get mixed up when using proxy and connection pooling

### ISSUE THREAD

**Issue by krystofbe** [benoitc/hackney#545]
Hello :)

I'm experiencing a strange issue with hackney in combination with a transparent http/https proxy and connection pooling.
I'm using ex_aws for different aws services. ex_aws uses hackney internally. i'm forced to connect through a transparent proxy with hackney. with proxy settings in hackney, i'm noticing that connections  get mixed up. 

i'm seeing requests for `https://s3.eu-central-1.amazonaws.com` being delivered to `https://sqs.eu-central-1.amazonaws.com` and vice versa when i'm sending a lot of requests in a short time. I'm pretty sure this is not an issue with ex_aws because this behavior disappears when i disable the proxy in `hackney_options` or disable connection pooling in hackney.

Can someone confirm this or do you need more background?

**Comment by benoitc** [comment]
can you provide a snippet of the code/conf you’re using? it doesn’t have to be the real host. Which tool are you usjng for the transparent proxy? any specific conf?

**Comment by thang911pk** [comment]
This is still an issue. Have you had a chance to take a look at it? We are using the latest version of hackney with HTTPoison.

**Comment by benoitc** [comment]
discussions continue in #566
