### ISSUE TITLE
Update mimerl dependency to ~>1.1 to let clients use the newer mimerl types

### ISSUE THREAD

**Issue by monkeydom** [benoitc/hackney#552]
Currently hackney requires 1.0.3 which disallows clients to use a newer version of mimerl themselves without overriding the dependency management.

**Comment by oladipo** [comment]
looks like there is a typo in the rebar.config file line 25.

The mimerl dependency is listed in a mix dependency format:

         {mimerl, "~>1.1"},

instead of 

         {mimerl, "1.1"}

**Comment by aboroska** [comment]
@oladipo Note that recent rebar3 versions do support the semver format: `{mimerl, "~> 1.1"},`

**Comment by oladipo** [comment]
Thanks @aboroska
