### ISSUE TITLE
Connect to IPv6 addresses

### ISSUE THREAD

**Issue by nroi** [benoitc/hackney#554]
Hackney supports connecting to a client by providing the IPv4 instead of its hostname:

    hackney:request(get, '78.46.175.29')

It also supports connecting to IPv6 hosts:

    hackney:request(get, 'ipv6.xnet.space')

But it fails when attempting to connect to an IPv6 host by providing is IPv6 address:

    hackney:request(get, '2a01:4f8:c0c:1de8::2')

I've tried different IPv6 notations, but hackney seems to assume that the given URL is either a hostname, or an IPv4 address.

If it were possible to connect to IPv6 addresses, this would also provide the possibility to implement something like "happy eyeballs" / RFC 8305 on top of hackney. I'm currently using hackney with a very crude workaround to decide whether to use IPv4 or IPv6 to connect to a host.

**Comment by benoitc** [comment]
normally the url should be given as hackney:request(get, "http://[2a01:4f8:c0c:1de8::2]"). But then there is an issue with IDNA that should be fixed.  I will take care of it later today :)

As eyeball, there is #206 opened long time ago . I aims to implement it but any PR is welcome :)

**Comment by benoitc** [comment]
idna error has been fixed in latest master.

**Comment by benoitc** [comment]
closing as done.
