### ISSUE TITLE
"Codepoint 95 not allowed" -- too restrictive

### ISSUE THREAD

**Issue by rlipscombe** [benoitc/hackney#557]
```
1> application:ensure_all_started(hackney).
2> hackney:request(get, hackney_url:make_url("http://foo_bar", [], []), [], [], []).
** exception exit: {bad_label,{alabel,"The label \"foo_bar\"  is not a valid A-label: ulabel error={bad_label,\n                                                           {context,\n                                                            \"Codepoint 95 not allowed ('DISALLOWED') at posion 3 in \\\"foo_bar\\\"\"}}"}}
     in function  idna:alabel/1 (src/idna.erl, line 277)
     in call from idna:encode_1/2 (src/idna.erl, line 145)
     in call from hackney_url:normalize/2 (src/hackney_url.erl, line 99)
     in call from hackney:request/5 (src/hackney.erl, line 306)
```

Underscores are allowed in hostnames: https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

Related to #534.

**Comment by rlipscombe** [comment]
Here's another counterexample:

```
$ curl http://docker_api_1.docker_default:8000
{"errors":[{"code":"NF003","status":"404","title":"Route Not Found","detail":"/ unknown."}]}
```

(ignore the error JSON; that's just to prove that something's on the other end)

**Comment by benoitc** [comment]
@rlipscombe hrm afaik IDN domain name can't include an underscore: https://tools.ietf.org/html/rfc5891#section-4.2.2 afaik `_` is in the disallowed chars.  You can use `-` in some conditions however. `docker-api-1.docker-default` is a valid domain.


Like some have said on the link you give, `_` is only used as prefix as described in [RFC 2782](https://tools.ietf.org/html/rfc2782)

>        The symbolic name of the desired service, as defined in Assigned
>        Numbers [STD 2] or locally.  An underscore (_) is prepended to
>        the service identifier to avoid collisions with DNS labels that
>       occur in nature.


But this service name is purely symbolic and won't be resolved at the end. So i'm thinking the error is OK.

**Comment by benoitc** [comment]
@rlipscombe also I'm confused, unix names or IP usage skip the idna check:

https://github.com/benoitc/hackney/blob/master/src/hackney_connect.erl#L40-L49

Do you still see an error when using a UNIX socket?

**Comment by rlipscombe** [comment]
Docker forces the underscores. I don't get to use `docker-api-1.docker-default`; it _is_ `docker_<foo>_1`.

**Comment by rlipscombe** [comment]
> Do you still see an error when using a UNIX socket?

I'm not using UNIX sockets.

**Comment by rlipscombe** [comment]
> domain name can't include an underscore

Whether the standard says they should or not is, unfortunately, irrelevant. They _do_, and other client software works fine.

**Comment by benoitc** [comment]
It's indeed interesting to see what curl does to bypass the spec there. Maybe it tries to resolve the domain after all.  

I will check. Do you have a simple to reproduce this error? That would help. Can you at least provide the headers it sends to that docker env? If you can provide the results of the following  command lines that would also help:

* `curl -i  http://docker_api_1.docker_default:8000`
* `curl -v  http://docker_api_1.docker_default:8000`

**Comment by benoitc** [comment]
if you can't gprovide a simple example, can you at least procides me some indications on how to obtain   such url?

**Comment by rlipscombe** [comment]
```
$ grep _ /etc/hosts
127.0.0.1       this_has_underscores
$ ping this_has_underscores
PING this_has_underscores (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.046 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.065 ms
```

```
$ curl http://this_has_underscores
<!DOCTYPE html>
...
```

```
$ curl -vv http://this_has_underscores/
*   Trying 127.0.0.1...
* Connected to this_has_underscores (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: this_has_underscores
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Mon, 25 Feb 2019 09:11:57 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Sun, 17 Dec 2017 20:19:35 GMT
< Connection: keep-alive
< ETag: "5a36d157-264"
< Accept-Ranges: bytes
< 
<!DOCTYPE html>
```

```
1> Url = hackney_url:make_url("http://this_has_underscores", [], []).
<<"http://this_has_underscores">>
2> hackney:request(get, Url, [], [], []).
** exception exit: {bad_label,{alabel,"The label \"this_has_underscores\"  is not a valid A-label: ulabel error={bad_label,\n                                                                        {context,\n                                                                         \"Codepoint 95 not allowed ('DISALLOWED') at posion 4 in \\\"this_has_underscores\\\"\"}}"}}
     in function  idna:alabel/1 (src/idna.erl, line 277)
     in call from idna:encode_1/2 (src/idna.erl, line 145)
     in call from hackney_url:normalize/2 (src/hackney_url.erl, line 99)
     in call from hackney:request/5 (src/hackney.erl, line 306)
```

**Comment by benoitc** [comment]
hrm it's a local host though. Anyway looking at url it seems to just ignore hosts that contains only ascii:
https://github.com/curl/curl/blob/7466d1a3083150da636251b156efbd520b01f1af/lib/url.c#L1728

which may explain why it works (though it shouldn't).

**Comment by benoitc** [comment]
as a side note you can't indeed register a domain name that have an underscore in it :)

**Comment by rlipscombe** [comment]
> it's a local host though

Only because I put it in `/etc/hosts` for demonstration purposes. I could wedge it into a dnsmasq config file... ;-)

My docker containers are down right now, because I'm in the middle of something else, so I can't demonstrate with those.

**Comment by whysoserious** [comment]
It would be great if we could have a configuration option in :hackney which would let to not to follow IDNA specification so closely. It's not respected in many use cases. I have exactly the same problem with docker images as Roger.

Anyway, thanks for the great work Benoit!

**Comment by rlipscombe** [comment]
> I have exactly the same problem with docker images

One of my colleagues correctly pointed out that, inside the docker network, the `docker_foo-bar_1` name is resolvable with just `foo-bar`, because of the implied service alias.

But that doesn't (in my case) help when attempting to access a container from the host with its full `docker_foo-bar_1.docker_default` name.

It occurs that there's some context missing here, for those not familiar with docker:

- The `docker_` part is a prefix added to the container name, based on the directory that the `docker-compose.yml` file is in (i.e., `docker`, in my case).
- The `_1` part is added implicitly (and might be `_2`, `_3` if you use `docker-compose --scale`).
- The `docker_default` network name comes from the same `docker_` prefix and the `default` network name. It's not needed inside the docker network.
- I have dnsmasq set up to forward queries from the host to the internal docker DNS server, so that I can use `foo.docker_default` (or `docker_foo_1.docker_default`) to access containers.

**Comment by rlipscombe** [comment]
> Anyway, thanks for the great work Benoit!

Absolutely!

**Comment by benoitc** [comment]
I see thanks for the explanation :) Please have a look in #558 and let me know if it works for you.

**Comment by benoitc** [comment]
fixed in master. I will make a release sometimes today.
