### ISSUE TITLE
1.15.1 fails on Windows

### ISSUE THREAD

**Issue by kotsius** [benoitc/hackney#559]
I am developing a Phoenix 1.4 project on a Windows 10 workstation with Elixir 1.8.1. Since upgrading hackney to 1.15.1, mix compile fails with:

===> Compiling certifi
===> Package certifi-2.5.1 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
==> prj
** (Mix) Could not compile dependency :hackney, "escript.exe "c:/Users/NAME_OF_USER/.mix/rebar3" bare compile --paths "PROJECT_PATH/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"

When I add {:hackney, "<= 1.15.0"} to my mix.exs, the compilation completes successfully. I do not know whether hackney is the dependency actually causing the problem, but I thought I should report this.

The output of rebar3.crashdump is:

Error: {badmatch,{error,{rebar_prv_update,package_index_download}}}
[{rebar_packages,handle_missing_package,3,
                 [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_packages.erl"},
                  {line,85}]},
 {rebar_app_utils,update_source,3,
                  [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                   {line,262}]},
 {rebar_app_utils,dep_to_app,7,
                  [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                   {line,228}]},
 {rebar_app_utils,'-parse_deps/6-lc$^0/1-0-',6,
                  [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                   {line,129}]},
 {rebar_app_discover,'-do/2-fun-0-',3,
                     [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                      {line,41}]},
 {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
 {rebar_app_discover,do,2,
                     [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                      {line,37}]},
 {rebar_prv_app_discovery,do,1,
                          [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_app_discovery.erl"},
                           {line,38}]}]

**Comment by benoitc** [comment]
It seems like an issue with mix or rebar3 or a plugin you are using. Did you report it to them?

**Comment by kotsius** [comment]
Thanks for your reply. A number of unrelated issues pointed to a wider problem. Reinstalling Windows, drastic as it was, seems to have resolved every issue.
