### ISSUE TITLE
How to disable pooling 

### ISSUE THREAD

**Issue by dowusu** [benoitc/hackney#598]
I'm new to Hackney,  I plan using it extensively. I was wondering if I can disable connection pooling. I understand hackney starts a default pool on startup. How can I disable this pool. I want a new connection everytime. Secondly how do I post xml to http using hackney in Elixir.

**Comment by benoitc** [comment]
just set the pool to false or none. for the pool. not sure wht-y you mean for the second, can't the xml be added as a body to the post request?

**Comment by dowusu** [comment]
Thanks for the swift response, initially had a challenge posting the xml, it was an oversight on my side. It's fine now. Keep up the good the work.
