### ISSUE TITLE
Failed to compile 1.16

### ISSUE THREAD

**Issue by ilkka** [benoitc/hackney#632]
I just came back to one repo after a few weeks of not doing anything, and I noticed that I couldn't compile it any more. This is what I was seeing doing `mix deps.compile` with DEBUG=1:

```
===> Package idna-6.0.1 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Fetching registry from "https://repo.hex.pm:443/registry.ets.gz?"
===> Writing registry to c:/Users/Ilkka/.cache/rebar3/hex/default/registry
===> Generating package index...
===> [appsignal:1.6.2], Bad dependency version for httpoison: ~> 0.11 or ~> 1.0.
===> [appsignal:1.6.6-beta.1], Bad dependency version for httpoison: ~> 0.11 or ~> 1.0.
[...]
===> [appsignal:1.6.4], Bad dependency version for httpoison: ~> 0.11 or ~> 1.0.
===> [batch_loader:0.1.0-beta.3], Bad dependency version for absinthe: ~> 1.4.0 or ~> 1.5.0-beta.
===> [appsignal:1.6.0-alpha.1], Bad dependency version for httpoison: ~> 0.11 or ~> 1.0.
===> Writing index to c:/Users/Ilkka/.cache/rebar3/hex/default/packages.idx
===> Package not found in registry: {<<"idna">>,<<"6.0.1">>}.
==> live_view_studio
** (Mix) Could not compile dependency :hackney, "escript.exe "c:/Users/Ilkka/.mix/rebar3" bare compile --paths="c:/Users/Ilkka/Code/my-project/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"
```

I'm getting hackney as a dependency of timex, which depends on `~> 1.0`. I added my own dependency to `{:hackney, "== 1.15.2"}` and that completely fixed the issue for me

I'm on Win 10 and `elixir --version` output is

```
Erlang/OTP 23 [erts-11.0] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.10.3 (compiled with Erlang/OTP 21)
```

**Comment by CatsOnFilm** [comment]
I suffered the same issue (on MacOS) and @ilkka 's solution worked for me also.

**Comment by ilkka** [comment]
Here's a minimal example that has the problem: https://github.com/ilkka/hackney_compile_test

All I did was `mix new` followed by adding the Hackney dep, and `mix deps.compile` fails.

**Comment by benoitc** [comment]
Hrm so did you try rather to add mix as dep to your app? I think mix need to be updated. I got the same issue until I upgraded rebar3 and I wonder if something changed in hex or such.  Let me know.

**Comment by ashutoshrishi** [comment]
I was getting compilation errors too on Macos (fine on Linux/CI). Had to re-install/update `rebar` via `mix local.rebar`, and everything compiles now.

**Comment by ilkka** [comment]
@ashutoshrishi 's procedure fixed it for me as well. Man, I wish there had been even a tiny indication somewhere in there about something being somehow out of date (I guess?).
