### ISSUE TITLE
Missing dep unicode_util_compat in tag 1.60.0

### ISSUE THREAD

**Issue by leonardb** [benoitc/hackney#663]
Tag 1.16.0 uses the `string_compat` module in `hackney_connection` and `hackney_ssl`

unicode_util_compat which provides string_compat is not included as a dep in rebar.config

**Comment by g-andrade** [comment]
This was fixed back in #634 but it hasn't yet been released under a tag.

**Comment by benoitc** [comment]
fixed in master.  It will be part of the new release
