### ISSUE TITLE
:hackney_url.pathencode should use uppercase hex

### ISSUE THREAD

**Issue by smanolloff** [benoitc/hackney#665]
According to [RFC3986](https://tools.ietf.org/html/rfc3986):

> The uppercase hexadecimal digits 'A' through 'F' are equivalent to
   the lowercase digits 'a' through 'f', respectively.  If two URIs
   differ only in the case of hexadecimal digits used in percent-encoded
   octets, they are equivalent.  **For consistency, URI producers and
   normalizers should use uppercase hexadecimal digits for all percent-
   encodings.**

Since it is recommended to use upper-case, it's better to also do it here.

**Comment by benoitc** [comment]
Good catch. 

That change is tricky to handle though at it my break some application relying on urls consistency or sort of by hashing them. The implementation will be done this way:

* add an option to path encoding to lowercase.
* default will be uppercase
* increment hackney minor release

**Comment by benoitc** [comment]
implemented via #671 . I decided to just make it the default in urlencode and produce uppercase using pathencode. The change will be documented as a braking change in the changelog.

**Comment by benoitc** [comment]
fixed in master. Thanks for the ticket!
