### ISSUE TITLE
Online doc link on hex.pm is 404

### ISSUE THREAD

**Issue by hassan** [benoitc/hackney#673]
https://hexdocs.pm/hackney/ is currently returning a 404. (The doc download link next to it works though.)

**Comment by benoitc** [comment]
yes. I don't know how to remove this lin since there shouldn't be one there. I will contact them.

**Comment by eproxus** [comment]
Would it be possible to upload the EDoc documentation there instead? I'm using [Dash](https://kapeli.com/dash) on macOS that can download documentation from Hex automatically and it would be neat to get Hackney documentation there too.

**Comment by benoitc** [comment]
I wish I would be able to remove that link. @eproxus unsure about it due to the current terms. I will think about it.

**Comment by eproxus** [comment]
Current terms? What are the issues with those?

**Comment by benoitc** [comment]
> Current terms? What are the issues with those?

``` by submitting, posting or displaying Content on or through the Services for public access, you grant us a worldwide, non-exclusive, royalty-free license to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such Content in any and all media or distribution methods (now known or later developed). Any Content you submit or post to the Services may be stored by Six Colors and will be subject to these terms indefinitely or until Six Colors, at its sole discretion, terminates the Content.```

While it's OK for the doc, I reserve the right to decide who can use the doc at some point.

**Comment by benoitc** [comment]
after discussing with some i decided to update hex.pm link with the API doc only (with the overview) as it is now. This has been published with latest version of hackney. Enjoy!

**Comment by eproxus** [comment]
Thank you! That really helps!
