### ISSUE TITLE
Set use_default_pool

### ISSUE THREAD

**Issue by spinettaro** [benoitc/hackney#682]
Hi,

I'm using Elixir and HTTPoison and I would like, for a test purpose, to disable the default pool as described in the main Readme. 
How can I set the hackney application environment key use_default_pool to false? 
I have a Elixir Phoenix project.

Thanks in advance

**Comment by benoitc** [comment]
apparently you can set it using the mix file. Hope it helps.

**Comment by benoitc** [comment]
http://blog.plataformatec.com.br/2016/05/how-to-config-environment-variables-with-elixir-and-exrm/

**Comment by Trevoke** [comment]
@spinettaro I am *guessing* that this would be `config :hackney, use_default_pool: false` but I am running into a frustrating `{:error, :closed}` that I can't get rid of (OpenAI package -> HTTPoison package -> Hackney package) and so I don't think this works... Did you get it to work?

**Comment by spinettaro** [comment]
@Trevoke yes that was what I did. If I remember well it worked for me `config :hackney, use_default_pool: false` in my config file
