### ISSUE TITLE
add unix domain socket support

### ISSUE THREAD

**Issue by benoitc** [benoitc/hackney#71]
Hackney should be able to support unix domain socket connections maybe by using https://github.com/msantos/procket.

**Comment by okeuday** [comment]
Might want to look at https://github.com/erlang/otp/pull/612

**Comment by benoitc** [comment]
@JonGretar no but looking at https://github.com/msantos/gen_unix it should be feasible to add it. I will add it once the work on the pool engine is done

**Comment by emilsoman** [comment]
@JonGretar looks like some work's being done on #336 for this 👍
