### ISSUE TITLE
GET request with basic authorization -- "HTTP request failed: bad_request"

### ISSUE THREAD

**Issue by human154** [benoitc/hackney#723]
I’m trying to get html from an old machine.

I’m able to successfully get a response on the command line with the following curl command (and I have a go program working as well):

```bash
curl 200.200.200.200/aaa/001 --user "user:password"`
```
Using Httpoison I get the error: “HTTP request failed: bad_request”:

```elixir
HTTPoison.start()

username = "user"
password = "password"

credentials_encoded = Base.encode64("#{username}:#{password}")

headers = [{"Authorization", "Basic #{credentials_encoded}"}]

case HTTPoison.get("200.200.200.200/aaa/001", headers) do
  {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
    IO.puts(body)
  {:ok, %HTTPoison.Response{status_code: status_code}} ->
    IO.puts("Received response with status code #{status_code}")
  {:error, %HTTPoison.Error{reason: reason}} ->
    IO.puts("HTTP request failed: #{reason}")
end
```

I asked about this on the elixir forum (https://elixirforum.com/t/httpoison-get-request-with-basic-authorization-http-request-failed-bad-request/57470/3) and was told that it is likely because the response contains '\n' instead of '\r\n':
```
    0000: 48 54 54 50 2f 31 2e 30 20 32 30 30 20 4f 4b 0a HTTP/1.0 200 OK.

curl appears to tolerate just sending \n, but Hackney will not. The [spec 2](https://www.w3.org/Protocols/HTTP/1.0/spec#Response) requires \r\n.
```

My understanding being that '0a', the last of the hex values indicates a LF (line feed) value and the spec calls for CR (carriage returen hex '0d') and LF.

If this is the issue which causes the error message.. even if hackney is "following the spec", from my perspective as a user, curl and go just  ‘worked’ with no issue, in terms of getting the job done for me, while I seem to have no way to move forward in elixir with httpoison.

Any feedback is appreciated. Thanks!

**Comment by benoitc** [comment]
this has been fixed in latest release. Closing the issue. If you happen to reproduce it still let me know.

**Comment by human154** [comment]
Thank you!!!

**Comment by apoorv-2204** [comment]
Apologies to reopen this conversation.

I am trying to download Maxmind db from permalinks, (free tier) using username and password. And I am getting the same error 400. While the same request converted to curl , seems to work fine and same for the postman

**Comment by apoorv-2204** [comment]
The code is for fetching geo infomration from ip, using maxmind db ,
mmdb provider map looks something like this.
```elixir
config :core, Core.Services.Mmdb,
  provider: %{
    uri: "MMDB_URI",
    name: "MMDB_PROVIDER",
    api_secret: "MMDB_API_SECRET",
    client_id: "MMDB_CLIENT_ID",
    type: "MMDB_SERVICE_TYPE"
  }
```
export MMDB_PROVIDER=MAXMIND
export MMDB_API_SECRET=LICENSCE KEY
export MMDB_CLIENT_ID=ACCOUNT_ID
export MMDB_TYPE="GeoLite2-Country"
# export MMDB_SERVICE_URI="https://download.maxmind.com/geoip/databases/GeoLite2-Country/download?suffix=tar.gz"
export MMDB_URI="https://download.maxmind.com/geoip/databases/"

The lice and account id can be acquired free of cost from maxmind website
